import React,{useEffect,useRef,useState}from'react'
import{categoryLabel,dateLabel,timeLabel,safeURL,specificMedia}from'./compact-display.js'
export default function CompactDetail({item,type,onClose,onSave,saved,onPlan,onShare,onFollow,following,taxonomy}){
 const[data,setData]=useState(item),[failed,setFailed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),root=useRef(null)
 const event=type==='event',title=event?data.title:data.name,photo=specificMedia(event?data.image_url:data.hero_image)
 useEffect(()=>{const c=new AbortController();setData(item);setFailed(false);const previous=document.activeElement;root.current?.focus();const escape=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=[...root.current.querySelectorAll('button:not([disabled]),a[href],input,select,textarea')].filter(x=>x.offsetParent!==null);if(!nodes.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus()}}};document.addEventListener('keydown',escape);if(!event)fetch(`/api/compact-detail?type=venue&id=${encodeURIComponent(item.id)}`,{signal:c.signal}).then(r=>r.ok?r.json():null).then(d=>{if(d?.item&&!c.signal.aborted)setData({...item,...d.item})}).catch(()=>{});return()=>{c.abort();document.removeEventListener('keydown',escape);previous?.focus?.()}},[item.id,item.event_key])
 const action=event?safeURL(data.ticket_url):safeURL(data.booking_link||data.website)
 const directions=data.address||data.venue_address
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{await onSave()}catch{setError('Could not update Saved. Please retry.')}finally{setBusy(false)}}
 return <div className="gt5-overlay gt-complete-overlay"><article ref={root} tabIndex={-1} className="gt5-detail gt-complete-detail" role="dialog" aria-modal="true" aria-label={title}>
 <header className="gt-complete-detail-bar"><button className="gt5-detail-back" onClick={onClose} aria-label="Back to results">←</button><span>{event?'Event':'Place'} · Atlanta</span><button onClick={onShare}>Share</button></header>
 {photo&&!failed&&<img className="gt-complete-detail-photo" src={photo} alt="" onError={()=>setFailed(true)}/>}
 <div className="gt-complete-detail-body"><small>{categoryLabel(data.category_key,taxonomy)}</small><h1>{title}</h1><p className="gt-complete-detail-meta">{event?`${dateLabel(data.event_date)} · ${timeLabel(data.event_time)}`:[data.neighborhood,data.price_range].filter(Boolean).join(' · ')}</p>{event&&<p>{data.venue_name}</p>}
 <div className="gt-complete-detail-actions">{action&&<a className="primary" href={action} target="_blank" rel="noreferrer">{event?'View tickets':'Check availability'} ↗</a>}<button onClick={()=>onPlan(data,type)}>Add to plan ＋</button><button onClick={save} disabled={busy} aria-pressed={saved}>{busy?'Saving…':saved?'Saved ✓':'Save'}</button></div>
 {error&&<p role="alert">{error}</p>}
 <div className="gt-complete-fact-grid">{directions&&<div><small>Location</small><p>{directions}</p><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(directions)}`} target="_blank" rel="noreferrer">Directions ↗</a></div>}{data.hours_summary&&<div><small>Published hours</small><p>{data.hours_summary}</p><small>Confirm exceptions before going.</small></div>}{data.dress_code&&<div><small>Dress code</small><p>{data.dress_code}</p></div>}{data.age_requirement&&<div><small>Age</small><p>{data.age_requirement}</p></div>}{data.price_range&&<div><small>Price guide</small><p>{data.price_range}</p></div>}</div>
 {(data.description||data.long_desc||data.short_desc)&&<section><h2>Good to know</h2><p>{data.description||data.long_desc||data.short_desc}</p></section>}
 <div className="gt-complete-support-actions">{data.phone&&<a href={`tel:${String(data.phone).replace(/[^+\d]/g,'')}`}>Call</a>}{safeURL(data.website)&&<a href={safeURL(data.website)} target="_blank" rel="noreferrer">Website ↗</a>}{onFollow&&<button onClick={onFollow}>{following?'Following ✓':'Follow + alerts'}</button>}</div>
 {(safeURL(data.source_url)||data.verified_at)&&<section className="gt-complete-provenance"><h2>Source information</h2>{safeURL(data.source_url)&&<a href={safeURL(data.source_url)} target="_blank" rel="noreferrer">{data.source_name||'Listing source'} ↗</a>}{data.verified_at&&<p>Venue checked {dateLabel(data.verified_at.slice(0,10))}.</p>}</section>}
 <p className="gt-compact-note">Planning and saving do not reserve a place or purchase a ticket. Availability is confirmed by the venue or ticket provider.</p>
 </div></article></div>
}
