import React,{useEffect,useState}from'react'
import CompactVenueCard from'./CompactVenueCard.jsx'
import CompactEventCard from'./CompactEventCard.jsx'
import{dateLabel}from'./compact-display.js'
const uuid=v=>/^[0-9a-f-]{36}$/i.test(String(v||''))
export default function CompactSaved({saved,plans,venues,events,onVenue,onEvent,onPlan,onSave,onDiscover,view,onView,now}){
 const[details,setDetails]=useState({venues:[],events:[]}),[error,setError]=useState(''),[limit,setLimit]=useState(48),[retry,setRetry]=useState(0)
 useEffect(()=>{const c=new AbortController();setError('');const missing=type=>saved.slice(0,limit).filter(s=>s.item_type===type).map(s=>String(s.item_id).replace(/^show:/,'')).filter(uuid)
 Promise.all(['venue','event'].map(async type=>{const ids=missing(type);if(!ids.length)return[];const groups=[];for(let i=0;i<ids.length;i+=48){const r=await fetch(`/api/compact-detail?type=${type}&ids=${ids.slice(i,i+48).join(',')}`,{signal:c.signal});if(!r.ok)throw new Error('Saved details could not refresh. Your bookmarks are still here.');const d=await r.json();groups.push(...(d.items||[]))}return groups})).then(([v,e])=>{if(!c.signal.aborted)setDetails({venues:v,events:e})}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[saved,limit,retry])
 const vs=new Map([...venues,...details.venues].map(v=>[v.id,v])),es=new Map([...events,...details.events].map(e=>[e.event_key,e]))
 return <section className="gt5-saved gt-complete-saved"><header className="gt-complete-heading"><h1>Worth keeping</h1><button onClick={onDiscover}>Explore ↗</button></header><div className="gt-complete-plan-modes"><button className={view==='plans'?'active':''} onClick={()=>onView('plans')}>Plans · {plans.length}</button><button className={view!=='plans'?'active':''} onClick={()=>onView('items')}>Saved · {saved.length}</button></div>
 {view==='plans'?plans.length?<div className="gt-complete-grid">{plans.map(p=><button className="gt-complete-saved-plan" key={p.id} onClick={()=>onPlan(p)}><small>{dateLabel(p.itinerary_date)}</small><strong>{p.name||'Your Atlanta plan'}</strong><span>{(p.stops||[]).length} stops · {p.group_size||2} people</span><small>Open itinerary ↗</small></button>)}</div>:<div className="gt-compact-state"><h2>Your next plan belongs here</h2><p>Save a built itinerary to return to all of its stops.</p></div>:<>{error&&<p role="alert">{error} <button onClick={()=>setRetry(n=>n+1)}>Retry</button></p>}{saved.length?<div className="gt-complete-grid">{saved.slice(0,limit).map(s=>{const v=vs.get(s.item_id),e=es.get(s.item_id);return s.item_type==='venue'&&v?<CompactVenueCard key={s.id} venue={v} saved onOpen={()=>onVenue(v)} onSave={()=>onSave('venue',s.item_id)}/>:s.item_type==='event'&&e?<CompactEventCard key={s.id} event={e} saved now={now} onOpen={()=>onEvent(e)} onSave={()=>onSave('event',s.item_id)}/>:<article className="gt-compact-state" key={s.id}><h3>Saved {s.item_type}</h3><p>Not in current verified results. Your bookmark has not been removed.</p><button onClick={()=>onSave(s.item_type,s.item_id)}>Remove bookmark</button></article>})}</div>:<div className="gt-compact-state"><h2>Save something good</h2><p>Use the heart on a place or event to keep it here.</p><button onClick={onDiscover}>Explore Atlanta</button></div>}{saved.length>limit&&<button className="gt-compact-load-more" onClick={()=>setLimit(n=>n+48)}>Load more saved items</button>}</>}
 </section>
}
