import React,{useEffect,useMemo,useRef,useState}from'react'
import CompactEventCard from'./CompactEventCard.jsx'
import{loadCompactEvents,eventScope}from'../intelligence/compact-events-client.js'
import{categoryLabel,dateLabel,localDate,shiftDate,uniqueItems}from'./compact-display.js'
export default function CompactEventCollection({category='',subcategory='',query='',mode='upcoming',date='',taxonomy=[],savedKeys,onOpen,onSave,now=Date.now(),embedded=false,onBack,onSports}){
 const[when,setWhen]=useState(date),[localMode,setLocalMode]=useState(mode),[localCategory,setLocalCategory]=useState(category),[filters,setFilters]=useState(false)
 const[state,setState]=useState({items:[],cursor:null,status:'loading',error:''}),[retry,setRetry]=useState(0),seq=useRef(0),pageBusy=useRef(false)
 useEffect(()=>{setWhen(date);setLocalMode(mode);setLocalCategory(category)},[date,mode,category])
 const scope=useMemo(()=>eventScope({category:localCategory,subcategory:localCategory===category?subcategory:'',q:query,mode:localMode,date:when,to:when&&localMode!=='tonight'?when:'',limit:embedded?8:24}),[localCategory,subcategory,query,localMode,when,embedded])
 const signature=JSON.stringify(scope)
 useEffect(()=>{const n=++seq.current,c=new AbortController();pageBusy.current=false;setState({items:[],cursor:null,status:'loading',error:''});const t=setTimeout(()=>loadCompactEvents(scope,c.signal).then(data=>{if(n===seq.current&&!c.signal.aborted)setState({...data,items:uniqueItems(data.items,'event'),status:'success',error:''})}).catch(e=>{if(!c.signal.aborted&&n===seq.current)setState({items:[],cursor:null,status:'error',error:e.message})}),query?220:0);return()=>{clearTimeout(t);c.abort()}},[signature,retry])
 const more=async()=>{if(!state.next_cursor||pageBusy.current)return;pageBusy.current=true;const n=seq.current;setState(s=>({...s,status:'loading-more'}));try{const data=await loadCompactEvents({...scope,cursor:state.next_cursor});if(n===seq.current)setState(s=>({...data,items:uniqueItems([...s.items,...data.items],'event'),status:'success',error:''}))}catch(e){if(n===seq.current)setState(s=>({...s,status:'success',error:e.message}))}finally{pageBusy.current=false}}
 const title=embedded?'Events':localCategory?categoryLabel(localCategory,taxonomy):localMode==='tonight'?'Tonight in Atlanta':'Upcoming in Atlanta'
 const groups=useMemo(()=>{if(embedded||localMode==='tonight')return [['',state.items]];const result=new Map();for(const e of state.items){const k=e.event_date||'TBA';if(!result.has(k))result.set(k,[]);result.get(k).push(e)}return[...result]},[state.items,embedded,localMode])
 return <section className={`gt-complete-event-collection ${embedded?'embedded':''}`} aria-label={title}>
  <header className="gt-complete-heading">{onBack&&<button className="gt-complete-back" onClick={onBack} aria-label="Back to Home">‹</button>}<div><h2>{title}</h2>{!embedded&&<p>{when?dateLabel(when):localMode==='tonight'?'Selected Atlanta evening':'Plan ahead, your way.'}</p>}</div><button className="gt-complete-filter-button" aria-label="Filter events" aria-expanded={filters} onClick={()=>setFilters(!filters)}>Filters</button></header>
  {filters&&<div className="gt-complete-filters"><label>Date<input type="date" value={when} min={localDate(now)} onChange={e=>{setWhen(e.target.value);setLocalMode('upcoming')}}/></label>{!embedded&&<label>Category<select value={localCategory} onChange={e=>setLocalCategory(e.target.value)}><option value="">All event categories</option>{taxonomy.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<button onClick={()=>{setWhen('');setLocalMode(mode);setLocalCategory(category)}}>Reset filters</button></div>}
  {category==='sports_watch'&&onSports&&<button className="gt-complete-inline-cta" onClick={onSports}>Teams, schedules & places to watch <span>↗</span></button>}
  {state.status==='loading'?<div className="gt-compact-skeleton-grid" role="status" aria-label="Loading events">{[1,2,3,4].map(n=><div key={n}/>)}</div>:state.status==='error'?<div className="gt-compact-state" role="alert"><h3>Events couldn’t refresh</h3><p>{state.error}</p><button onClick={()=>setRetry(r=>r+1)}>Retry events</button></div>:!state.items.length?<div className="gt-compact-state"><h3>{state.next_cursor?'Keep exploring this collection':'No events for this selection'}</h3><p>{localMode==='tonight'?'No current evening events match. Explore another date or browse places; venue hours must be checked separately.':'Try another date or category. We never fill a collection with unrelated events.'}</p>{state.next_cursor&&<button onClick={more}>Continue searching events</button>}{!embedded&&<button onClick={()=>{setWhen('');setLocalMode('upcoming');setLocalCategory('')}}>Explore upcoming</button>}</div>:<>
   {groups.map(([d,items])=><section key={d||'events'}>{d&&<h3 className="gt-complete-date-heading">{dateLabel(d)}</h3>}<div className="gt-complete-grid">{items.map(e=><CompactEventCard key={e.event_key} event={e} taxonomy={taxonomy} now={now} saved={savedKeys?.has(`event:${e.event_key}`)} onOpen={()=>onOpen(e)} onSave={()=>onSave('event',e.event_key)}/>)}</div></section>)}
   {state.error&&<p role="alert">{state.error}</p>}{state.next_cursor&&<button className="gt-compact-load-more" disabled={state.status==='loading-more'} onClick={more}>{state.status==='loading-more'?'Loading…':'Load more events'}</button>}
  </>}
  {state.degraded&&<p className="gt-compact-note">Recently verified snapshot · refresh when connected.</p>}
 </section>
}
