import React,{useEffect,useRef,useState}from'react'
import ShakeRestaurantPanel from'./ShakeRestaurantPanel.jsx'
import{compactPlanRequest}from'../intelligence/compact-plan-client.js'
import{localDate,dateLabel,timeLabel}from'./compact-display.js'
import{categoryEditorialMedia}from'./good-times-editorial-media.js'
const OPTIONS=[['grown','Grown & sexy','lounge'],['turnt','Turn up','nightlife'],['date','Date night','dating'],['live','Live music','live music'],['food','Food first','dining'],['culture','Culture','culture'],['rooftop','Rooftop','rooftop'],['explore','Something different','entertainment'],['sports','Game night','sports'],['family','Family time','family']]
export default function CompactPlanHub({venues,events,onVenue,onEvent,onResult,initial,now,session}){
 const[mode,setMode]=useState('guided'),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ask,setAsk]=useState(''),controller=useRef(null)
 const fresh=()=>({date:initial?.event_date||localDate(now),start:initial?.event_time?`${String(Math.max(0,Number(initial.event_time.slice(0,2))-2)).padStart(2,'0')}:00`:'19:00',end:'01:00',people:2,vibes:[],lead:'',area:'',budget:'any',needs:[],age:'',pinned:initial?.type==='venue'?initial.id:null,event:initial?.type==='event'?initial.event_key:null})
 const[value,setValue]=useState(fresh)
 const storageKey=`gt_complete_plan_draft:${session?.user?.id||'signed-out'}`
 useEffect(()=>{try{if(!initial){const raw=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(raw?.date>=localDate(now))setValue({...fresh(),...raw})}}catch{}return()=>controller.current?.abort()},[])
 useEffect(()=>{if(initial){setValue(fresh());setStep(0);setMode('guided')}},[initial?.id,initial?.event_key])
 useEffect(()=>{try{sessionStorage.setItem(storageKey,JSON.stringify(value))}catch{}},[value,storageKey])
 const change=patch=>setValue(v=>({...v,...patch}))
 const toggle=id=>{const values=value.vibes.includes(id)?value.vibes.filter(x=>x!==id):value.vibes.length<4?[...value.vibes,id]:value.vibes;change({vibes:values,lead:values.includes(value.lead)?value.lead:values[0]||''})}
 const build=async()=>{if(busy)return;setBusy(true);setError('');controller.current=new AbortController();try{const response=await compactPlanRequest({action:'generate',input:{...value,query:mode==='ask'?ask:''}},controller.current.signal);onResult(response.itinerary)}catch(e){if(e.name!=='AbortError')setError(e.message)}finally{setBusy(false)}}
 const next=()=>{setError('');if(step===0&&!value.vibes.length){setError('Choose at least one vibe.');return}if(step===1&&(!value.date||!value.start||!value.end||value.people<1)){setError('Choose a date, times and group size.');return}setStep(s=>Math.min(3,s+1))}
 const areas=[...new Set(venues.map(v=>v.neighborhood).filter(Boolean))].sort()
 return <section className="gt-complete-planner"><header className="gt-complete-heading"><h1>Build My Night</h1><span>Your night. Your choices.</span></header>
 <nav className="gt-complete-plan-modes" aria-label="Choose a planning method">{[['guided','Build it'],['shake','Shake it'],['ask','Ask for it']].map(([id,label])=><button key={id} className={mode===id?'active':''} aria-pressed={mode===id} onClick={()=>{setMode(id);setError('')}}>{label}</button>)}</nav>
 {initial&&(value.pinned||value.event)&&<div className="gt-complete-notice"><span>Planning around <strong>{initial.name||initial.title}</strong></span><button onClick={()=>change({pinned:null,event:null})}>Unlock</button></div>}
 {mode==='shake'?<ShakeRestaurantPanel city="Atlanta" venues={venues} onOpen={onVenue} session={session} onBuild={venue=>{change({pinned:venue.id,vibes:['food'],lead:'food'});setMode('guided');setStep(1)}}/>:mode==='ask'?<div className="gt-complete-ask"><h2>What sounds good?</h2><p>Describe your idea, then confirm the date and practical details below.</p><textarea aria-label="Describe your night" value={ask} onChange={e=>{setAsk(e.target.value);const t=e.target.value.toLowerCase(),v=OPTIONS.filter(([id,label])=>t.includes(label.toLowerCase())||t.includes(id)).map(([id])=>id);if(v.length)change({vibes:v.slice(0,4),lead:v[0]})}} placeholder="Dinner and live music, somewhere in Midtown…"/><button onClick={()=>{const t=ask.toLowerCase();const vibes=[];if(/food|dinner|brunch/.test(t))vibes.push('food');if(/live|concert|jazz/.test(t))vibes.push('live');if(/date|romantic/.test(t))vibes.push('date');if(/club|party|turn up/.test(t))vibes.push('turnt');const area=areas.find(a=>t.includes(a.toLowerCase()));change({vibes:vibes.length?vibes:['explore'],lead:vibes[0]||'explore',area:area||value.area});setMode('guided');setStep(1)}} disabled={!ask.trim()}>Review my preferences →</button><p className="gt-compact-note">Only recognized preferences are carried forward. Review them before building; we do not guess bookings or availability.</p></div>:<>
 <ol className="gt-complete-steps">{['Vibe','Basics','Preferences','Review'].map((label,i)=><li key={label}><button disabled={i>step} className={step===i?'active':''} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><b>{i+1}</b>{label}</button></li>)}</ol>
 {step===0&&<><h2>Choose up to four vibes</h2><div className="gt-complete-vibes">{OPTIONS.map(([id,label,category])=><button key={id} type="button" aria-pressed={value.vibes.includes(id)} className={value.vibes.includes(id)?'active':''} style={{'--vibe-photo':`url("${categoryEditorialMedia(category,[],'atlanta')}")`}} onClick={()=>toggle(id)}><strong>{label}</strong><span>{value.vibes.includes(id)?'✓':'＋'}</span></button>)}</div>{value.vibes.length>1&&<label className="gt-complete-field">Lead vibe<select value={value.lead} onChange={e=>change({lead:e.target.value})}>{OPTIONS.filter(([id])=>value.vibes.includes(id)).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}</>}
 {step===1&&<><h2>Set the basics</h2><div className="gt-complete-form-grid"><label>Date<input type="date" aria-label="Plan date" value={value.date} min={localDate(now)} onChange={e=>change({date:e.target.value})}/></label><label>People<input type="number" aria-label="People" value={value.people} min="1" max="50" onChange={e=>change({people:Number(e.target.value)})}/></label><label>Start<input type="time" aria-label="Start time" value={value.start} onChange={e=>change({start:e.target.value})}/></label><label>Finish<input type="time" aria-label="Finish time" value={value.end} onChange={e=>change({end:e.target.value})}/></label></div><p className="gt-compact-note">A finish earlier than the start means after midnight.</p></>}
 {step===2&&<><h2>Make it yours</h2><div className="gt-complete-form-grid"><label>Area<select aria-label="Plan area" value={value.area} onChange={e=>change({area:e.target.value})}><option value="">Anywhere in Atlanta</option>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Spending preference<select aria-label="Spending preference" value={value.budget} onChange={e=>change({budget:e.target.value})}><option value="any">No preference</option><option value="value">Keep it affordable</option><option value="mid">Mid-range</option><option value="premium">Premium</option></select></label><label>Youngest guest age (optional)<input type="number" aria-label="Youngest guest age" min="0" max="120" value={value.age??''} onChange={e=>change({age:e.target.value})}/></label></div><p>Must-have requirements</p><div className="gt-complete-checks">{[['wheelchair_accessible','Wheelchair-accessible'],['vegetarian','Vegetarian options'],['vegan','Vegan options']].map(([id,label])=><label key={id}><input type="checkbox" checked={value.needs.includes(id)} onChange={()=>change({needs:value.needs.includes(id)?value.needs.filter(x=>x!==id):[...value.needs,id]})}/>{label}</label>)}</div><p className="gt-compact-note">Must-haves require supporting venue information. We will not label unknown accessibility or dietary options as confirmed.</p></>}
 {step===3&&<><h2>Review your night</h2><dl className="gt-complete-review"><dt>When</dt><dd>{dateLabel(value.date)}<br/>{timeLabel(value.start)} – {timeLabel(value.end)}</dd><dt>Group</dt><dd>{value.people} people</dd><dt>Vibes</dt><dd>{OPTIONS.filter(([id])=>value.vibes.includes(id)).map(([,label])=>label).join(' · ')}</dd><dt>Area</dt><dd>{value.area||'Anywhere in Atlanta'}</dd><dt>Spending</dt><dd>{value.budget}</dd><dt>Youngest guest</dt><dd>{value.age!==''&&value.age!=null?`${value.age} years`:'Not specified; check admission rules'}</dd><dt>Must-haves</dt><dd>{value.needs.length?value.needs.join(', ').replaceAll('_',' '):'None selected'}</dd></dl><p className="gt-compact-note">Plans are recommendations. Hours, travel and prices requiring confirmation will be clearly identified. Nothing is booked automatically.</p></>}
 {error&&<p className="gt-complete-error" role="alert">{error}</p>}
 <div className="gt-complete-step-actions">{step>0&&<button disabled={busy} onClick={()=>setStep(s=>s-1)}>Back</button>}<button className="primary" disabled={busy} onClick={step===3?build:next}>{busy?'Building your plan…':step===3?'Build my night →':'Continue →'}</button></div>
 </>}
 </section>
}
