import React,{useEffect,useRef,useState}from'react'
import{compactPlanRequest}from'../intelligence/compact-plan-client.js'
import{calendarFile,dateLabel,timeLabel,safeURL,specificMedia,qualifiedStatus}from'./compact-display.js'
import{shareContent}from'../../native.js'
export default function CompactItinerary({plan,onClose,onSaved}){
 const[value,setValue]=useState(()=>structuredClone(plan)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[swap,setSwap]=useState(null),[options,setOptions]=useState([]),[dirty,setDirty]=useState(false),root=useRef(null),dirtyRef=useRef(false),[confirmClose,setConfirmClose]=useState(false)
 dirtyRef.current=dirty||!value.updated_at
 const close=()=>{if(dirtyRef.current)setConfirmClose(true);else onClose()}
 useEffect(()=>{const previous=document.activeElement;root.current?.focus();const key=e=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(dirtyRef.current)setConfirmClose(true);else onClose()}if(e.key==='Tab'){const nodes=[...root.current.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),summary,[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===root.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus?.()}},[])
 const update=stops=>{setValue(v=>({...v,stops}));setDirty(true);setNotice('Changes are not saved yet. Recheck stop times after moving or replacing a place.')}
 const move=(index,delta)=>{const next=[...value.stops],to=index+delta;if(to<0||to>=next.length||next[index].locked||next[to].locked)return;[next[index],next[to]]=[next[to],next[index]];update(next)}
 const replace=async index=>{if(busy)return;setBusy(true);setError('');setSwap(index);try{const result=await compactPlanRequest({action:'alternatives',input:value.metadata?.spec||{date:value.itinerary_date,people:value.group_size}});setOptions(result.venues.filter(v=>!value.stops.some(s=>s.id===`venue:${v.id}`)))}catch(e){setError(e.message);setSwap(null)}finally{setBusy(false)}}
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{const result=await compactPlanRequest({action:'save',plan:value});setValue(result.itinerary);setDirty(false);setNotice('Plan saved to your account.');onSaved(result.itinerary)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const calendar=()=>{try{const blob=new Blob([calendarFile(value)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='GOOD_TIMES_plan.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Calendar file prepared. These remain suggested stops.')}catch(e){setError(e.message)}}
 const share=async()=>{await shareContent({title:value.name,text:[value.name,dateLabel(value.itinerary_date),'Suggested plan — not booked',...value.stops.map((s,i)=>`${i+1}. ${timeLabel(s.time)} · ${s.name}`)].join('\n'),dialogTitle:'Share your plan'})}
 return <div className="gt5-overlay gt-complete-overlay"><article className="gt5-itinerary gt-complete-itinerary" ref={root} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Your Atlanta plan"><header className="gt-complete-detail-bar"><button className="gt5-detail-back" onClick={close} aria-label="Close itinerary">←</button><span>YOUR GOOD TIMES</span><button onClick={share}>Share</button></header><div className="gt-complete-itinerary-body">{confirmClose&&<section role="alert" className="gt-complete-plan-warning"><strong>Leave without saving?</strong><p>Your latest changes have not been saved to your account.</p><div className="gt-complete-itinerary-actions"><button className="primary" onClick={()=>setConfirmClose(false)}>Keep editing</button><button onClick={onClose}>Discard changes</button></div></section>}<h1>{value.name}</h1><p>{dateLabel(value.itinerary_date)} · {value.group_size||2} people · {value.stops.length} stops</p>
 <div className="gt-complete-plan-warning"><strong>Suggested, not booked</strong><p>Check hours, travel and prices before going.</p></div>
 <ol className="gt-complete-timeline">{value.stops.map((s,i)=><li key={s.id}><header><b>{String(i+1).padStart(2,'0')}</b><label><span className="gt-compact-sr">Time for {s.name}</span><input type="time" value={s.time||''} disabled={s.type==='event'||s.locked} onChange={e=>update(value.stops.map((v,k)=>k===i?{...v,time:e.target.value}:v))}/></label><small>{qualifiedStatus(s)}</small></header><div className="gt-complete-stop-content">{specificMedia(s.image_url||s.image)&&<img src={specificMedia(s.image_url||s.image)} alt="" onError={e=>e.currentTarget.style.display='none'}/>}<div><small>{s.role||s.type}</small><h2>{s.name}</h2><p>{s.neighborhood||s.venue}</p>{safeURL(s.ticket_url||s.booking_link||s.website)&&<a href={safeURL(s.ticket_url||s.booking_link||s.website)} target="_blank" rel="noreferrer">{s.ticket_url?'View tickets':'Check availability'} ↗</a>}</div></div><div className="gt-complete-stop-tools"><button aria-pressed={Boolean(s.locked)} onClick={()=>update(value.stops.map((v,k)=>k===i?{...v,locked:!v.locked}:v))}>{s.locked?'Locked ✓':'Lock'}</button><button onClick={()=>replace(i)} disabled={busy||s.locked}>Swap</button><button aria-label={`Move ${s.name} earlier`} disabled={i===0||s.locked||value.stops[i-1]?.locked} onClick={()=>move(i,-1)}>↑</button><button aria-label={`Move ${s.name} later`} disabled={i===value.stops.length-1||s.locked||value.stops[i+1]?.locked} onClick={()=>move(i,1)}>↓</button><button disabled={s.locked||value.stops.length===1} onClick={()=>update(value.stops.filter((_,k)=>i!==k))}>Remove</button></div></li>)}</ol>
 {swap!==null&&<section className="gt-complete-swap"><header className="gt-complete-heading"><h2>Choose a replacement</h2><button onClick={()=>setSwap(null)}>Cancel</button></header>{busy?<p role="status">Finding eligible alternatives…</p>:options.length?options.map(v=><button key={v.id} onClick={()=>{update(value.stops.map((s,i)=>i===swap?{id:`venue:${v.id}`,type:'venue',name:v.name,venue:v.name,neighborhood:v.neighborhood,address:v.address,time:s.time,date:s.date,role:s.role,status:'SUGGESTED',image_url:v.hero_image,booking_link:v.booking_link,website:v.website,locked:false}:s));setSwap(null)}}><strong>{v.name}</strong><small>{v.neighborhood||'Atlanta'} ↗</small></button>):<p>No other verified places match. Change your plan preferences rather than relaxing them silently.</p>}</section>}
 {value.metadata?.warnings?.length>0&&<details className="gt-complete-plan-checks"><summary>What to confirm ({value.metadata.warnings.length})</summary>{value.metadata.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
 {error&&<p role="alert" className="gt-complete-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="gt-complete-itinerary-actions"><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':value.updated_at&&!dirty?'Saved · Save again':'Save plan'}</button><button onClick={calendar}>Add to calendar</button><button onClick={share}>Share plan</button></div>
 </div></article></div>
}
