import React,{useEffect,useMemo,useRef,useState} from 'react'
import { HOME_MODES,cityDate,diversePicks,isLeisureEvent,isExplicitlyFamily,planBucket,safePublicUrl,sportPresentation } from './good-times-ux-model.js'
import { hardenDisplayInventory } from './good-times-media-uniqueness.js'
import { withReviewedVenueMedia } from './good-times-reviewed-media.js'
const titleOf=x=>x.title||x.name||'GOOD TIMES'
const dateLabel=value=>value?new Date(`${value}T12:00:00`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'}):'Date to confirm'
function timeLabel(value){if(!value)return 'Time to confirm';const match=String(value).match(/^(\d{1,2}):(\d{2})/);if(!match)return value;const hour=Number(match[1]);return `${hour%12||12}:${match[2]} ${hour>=12?'PM':'AM'}`}
const CATEGORY_LABELS={concerts_live_music:'Live music',attractions_experiences:'Experiences',festivals_major_activations:'Festivals',comedy_performing_arts:'Comedy & shows',arts_museums_culture:'Arts & culture',dining_culinary:'Food & drink',family_kids:'Family',sports_watch:'Sports',day_parties_brunch:'Brunch & day parties'}
const typeLabel=value=>CATEGORY_LABELS[value]||String(value||'Experience').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
function Section({title,kicker,action,children}) { return <section className="gt-ux-section"><header><div>{kicker&&<span>{kicker}</span>}<h2>{title}</h2></div>{action}</header>{children}</section> }
export function UXCard({item,type='event',saved,onOpen,onSave,compact=false}) {
  const image=safePublicUrl(type==='event'?item.image_url:item.hero_image)
  return <article className={`gt-ux-card ${compact?'compact':''}`}><button className="gt-ux-card-open" onClick={()=>onOpen(item)}><div className="gt-ux-card-image">{image?<img src={image} alt="" loading="lazy"/>:<div className="gt-ux-image-empty" aria-label="Photo unavailable">GT</div>}{type==='event'&&<span>{dateLabel(item.event_date)}</span>}</div><div className="gt-ux-card-info"><small>{typeLabel(item.category_key)}</small><h3>{titleOf(item)}</h3><p>{type==='event'?`${timeLabel(item.event_time)} · ${item.venue_name||'Location to confirm'}`:item.neighborhood||'Atlanta'}</p>{type==='venue'&&<p>{[item.price_range,item.google_rating?`★ ${Number(item.google_rating).toFixed(1)}`:null].filter(Boolean).join(' · ')||'View place details'}</p>}</div></button>{onSave&&<button className={`gt-ux-bookmark ${saved?'active':''}`} aria-label={`${saved?'Unsave':'Save'} ${titleOf(item)}`} aria-pressed={!!saved} onClick={()=>onSave(type,type==='event'?item.event_key:item.id)}>{saved?'✓':'♡'}</button>}</article>
}
function SearchBox({value,onChange,onSubmit,label='Search GOOD TIMES',placeholder='Search the city…'}) { return <form className="gt-ux-search" role="search" onSubmit={e=>{e.preventDefault();onSubmit?.()}}><span aria-hidden="true">⌕</span><input type="search" aria-label={label} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)} maxLength={100}/>{onSubmit&&<button type="submit" aria-label="Search">→</button>}</form> }
export function SportsView({compact=false,onExpand,onPlan}) {
  const[data,setData]=useState(null),[error,setError]=useState(''),[team,setTeam]=useState(''),[homeOnly,setHomeOnly]=useState(false),[attempt,setAttempt]=useState(0),[clock,setClock]=useState(Date.now())
  useEffect(()=>{let live=true;const controller=new AbortController();const load=async()=>{if(document.hidden)return;try{const response=await fetch('/api/home-sports',{signal:controller.signal});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'Sports updates are unavailable.');if(live){setData(payload);setError('');setClock(Date.now())}}catch(err){if(live&&err.name!=='AbortError')setError(err.message)}};void load();const timer=setInterval(()=>{setClock(Date.now());void load()},60000);return()=>{live=false;controller.abort();clearInterval(timer)}},[attempt])
  const all=data?.games||[],games=all.filter(game=>(!team||String(`${game.home_team} ${game.away_team}`).includes(team))&&(!homeOnly||/^Atlanta /.test(game.home_team||''))),shown=compact?games.slice(0,2):games
  return <section className={`gt-ux-sports ${compact?'compact':''}`} aria-label="Atlanta sports"><header><div><span className="gt-ux-eyebrow">HOME TEAMS · HOME & AWAY</span><h2>Your city. Your teams.</h2></div>{compact&&<button onClick={onExpand}>Sports →</button>}</header>
    {!compact&&<><p>Schedules and scores, with source freshness shown. Never a guessed score.</p><div className="gt-ux-chips" aria-label="Choose a team"><button aria-pressed={!team} onClick={()=>setTeam('')}>All teams</button>{(data?.teams||[]).map(row=><button key={row.id} aria-pressed={team===row.name} onClick={()=>setTeam(team===row.name?'':row.name)}>{row.name.replace(/^Atlanta /,'')} <small>{row.league}</small></button>)}</div><label className="gt-ux-toggle"><input type="checkbox" checked={homeOnly} onChange={e=>setHomeOnly(e.target.checked)}/> Home games only</label></>}
    {error&&<div className="gt-ux-message" role="status"><p>{error}</p><button onClick={()=>setAttempt(x=>x+1)}>Retry sports</button></div>}
    {!data&&!error&&<p className="gt-ux-status" role="status">Checking team schedules…</p>}
    {data&&!shown.length&&<p className="gt-ux-note">No current games are available for this selection. This is a coverage gap, not a claim that no games are scheduled.</p>}
    <div className="gt-ux-score-list">{shown.map(game=>{const state=sportPresentation(game,clock);return <article className="gt-ux-score" key={game.id}><header><span>{game.league} · {dateLabel(game.game_date)}</span><strong className={state.live?'live':''}>{state.label}</strong></header><div className="gt-ux-score-team"><span>{game.away_team}</span><b>{state.showScores?game.away_score:'—'}</b></div><div className="gt-ux-score-team"><span>{game.home_team}</span><b>{state.showScores?game.home_score:'—'}</b></div><p>{timeLabel(game.game_time)} ET · {game.venue||'Venue to confirm'}</p><small>{state.updatedAt?`Source updated ${new Date(state.updatedAt).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})} ET`:'Source update time unavailable'}</small>{!compact&&state.scheduleFresh&&onPlan&&<button onClick={()=>onPlan(`Help plan around ${game.away_team} at ${game.home_team} on ${game.game_date}. Confirm the schedule and venue before recommending attendance.`)}>Plan around this game →</button>}</article>})}</div>
    {!compact&&data?.coverage&&<p className="gt-ux-note">{data.coverage}</p>}
  </section>
}
export function HomeView({mode,onMode,events,today,upcoming,venues,savedKeys,onEvent,onVenue,onSave,onExplore,onPlan,heroImage,plans=[],onPlanOpen}) {
  const[search,setSearch]=useState(''),picks=useMemo(()=>diversePicks(events,venues,5),[events,venues]),family=useMemo(()=>[...events.map(item=>({type:'event',item})),...venues.map(item=>({type:'venue',item}))].filter(row=>isExplicitlyFamily(row.item)).slice(0,4),[events,venues])
  const continuing=plans.find(p=>planBucket(p)==='upcoming')||plans.find(p=>planBucket(p)==='drafts')
  const leisureUpcoming=upcoming.filter(isLeisureEvent),rows=(mode==='tonight'?today:upcoming).filter(isLeisureEvent)
  return <section className="gt-ux-home"><header className="gt-ux-homehead" style={{'--ux-art':`url("${heroImage||''}")`}}><span>ATLANTA · {dateLabel(cityDate()).toUpperCase()}</span><h1>Your city.<br/><em>More good times.</em></h1><p>Something worth doing. All day. All week.</p></header><SearchBox value={search} onChange={setSearch} onSubmit={()=>onExplore('entertainment',search)} placeholder="Events, food, places, neighborhoods…"/><nav className="gt-ux-home-modes" aria-label="GOOD TIMES Home views">{HOME_MODES.map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>onMode(id)}>{label}</button>)}</nav>
    {mode==='sports'?<SportsView onPlan={onPlan}/>:mode==='upcoming'||mode==='tonight'?<Section kicker={mode==='tonight'?'YOUR EVENING, AT A GLANCE':'THE CITY, IN ORDER'} title={mode==='tonight'?'Tonight in Atlanta':'Coming up in Atlanta'}><div className="gt-ux-rows">{rows.slice(0,30).map(event=><UXCard key={event.event_key} item={event} type="event" compact saved={savedKeys.has(`event:${event.event_key}`)} onOpen={onEvent} onSave={onSave}/>)}</div>{!rows.length&&<p className="gt-ux-note">No verified listings are available in this view right now. Explore the catalog for more options.</p>}</Section>:<>
      {continuing&&<button className="gt-ux-resume" onClick={()=>onPlanOpen(continuing)}><span>YOUR NEXT GOOD TIME<strong>{continuing.name||'Continue your plan'}</strong></span><b aria-hidden="true">↗</b></button>}
      <Section kicker="CURATED FOR YOUR DAY" title="Worth your time" action={<button onClick={()=>onExplore('entertainment','')}>See all →</button>}><div className="gt-ux-card-grid">{picks.map(({item,type})=><UXCard key={`${type}:${item.event_key||item.id}`} item={item} type={type} saved={savedKeys.has(`${type}:${item.event_key||item.id}`)} onOpen={type==='event'?onEvent:onVenue} onSave={onSave}/>)}</div>{!picks.length&&<p className="gt-ux-status">Current picks are loading. The catalog remains available above.</p>}</Section>
      <SportsView compact onExpand={()=>onMode('sports')}/>
      {family.length>0&&<Section kicker="GOOD TIMES FOR EVERYONE" title="Bring the family" action={<button onClick={()=>onExplore('entertainment','family')}>Explore →</button>}><div className="gt-ux-card-grid">{family.map(({item,type})=><UXCard key={`${type}:${item.event_key||item.id}`} item={item} type={type} saved={savedKeys.has(`${type}:${item.event_key||item.id}`)} onOpen={type==='event'?onEvent:onVenue} onSave={onSave}/>)}</div></Section>}
      <button className="gt-ux-plan-callout" onClick={()=>onPlan('')}><span><small>THE BEST PART IS GOING.</small><strong>Leave the planning to us.</strong><em>Click. Shake. Ask.</em></span><b aria-hidden="true">↗</b></button>
      <Section kicker="DATES WORTH KEEPING" title="Next up" action={<button onClick={()=>onMode('upcoming')}>The week →</button>}><div className="gt-ux-rows">{leisureUpcoming.slice(0,4).map(event=><UXCard key={event.event_key} item={event} type="event" compact saved={savedKeys.has(`event:${event.event_key}`)} onOpen={onEvent} onSave={onSave}/>)}</div></Section>
    </>}
  </section>
}
const CATEGORIES=[['','All'],['concerts_live_music','Live music'],['family_kids','Family'],['arts_museums_culture','Arts & culture'],['comedy_performing_arts','Comedy'],['nightlife','Nightlife'],['attractions_experiences','Experiences'],['dining_culinary','Food & drink'],['sports_watch','Sports']]
const VENUE_CATEGORIES=[['','All'],['dining_culinary','Food & drink'],['rooftops','Rooftops'],['lounges','Lounges'],['nightclubs','Nightclubs'],['hookah','Hookah'],['family_kids','Family'],['attractions_experiences','Activities'],['arts_museums_culture','Arts & culture'],['wellness_fitness','Wellness']]
export function DirectoryView({scope,visible=true,query,onQuery,savedKeys,onEvent,onVenue,onSave,heroImage}) {
  const categories=scope==='venues'?VENUE_CATEGORIES:CATEGORIES
  const[category,setCategory]=useState(''),[date,setDate]=useState(''),[page,setPage]=useState(0),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[more,setMore]=useState(false),[attempt,setAttempt]=useState(0)
  const generation=useRef(0),initial=useRef(true)
  useEffect(()=>{if(initial.current){initial.current=false;return}setPage(0);setItems([])},[scope,query,category,date])
  useEffect(()=>{if(!visible)return undefined;const revision=++generation.current,controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(async()=>{try{const params=new URLSearchParams({scope,q:query||'',category,date:scope==='entertainment'?date:'',page:String(page)});const response=await fetch(`/api/discovery-search?${params}`,{signal:controller.signal});const result=await response.json();if(!response.ok||!result?.ok)throw new Error(result?.error||'Search is temporarily unavailable.');const hardened=scope==='venues'?hardenDisplayInventory([],withReviewedVenueMedia(result.items||[])).venues:hardenDisplayInventory(result.items||[],[]).events;if(revision!==generation.current)return;setItems(current=>{const next=page===0?hardened:[...current,...hardened];return [...new Map(next.map(item=>[item.event_key||item.id,item])).values()]});setMore(result.has_more===true)}catch(err){if(revision===generation.current&&err.name!=='AbortError')setError(err.message)}finally{if(revision===generation.current)setLoading(false)}},query?300:0);return()=>{clearTimeout(timer);controller.abort()}},[scope,visible,query,category,date,page,attempt])
  return <section className="gt-ux-directory" aria-busy={loading}><header className="gt-ux-pagehead" style={{'--ux-art':`url("${heroImage||''}")`}}><span>EXPLORE ATLANTA</span><h1>{scope==='venues'?'Find your place.':'Find your good time.'}</h1><p>{scope==='venues'?'Restaurants, lounges, attractions and more.':'Events, performances and experiences.'}</p></header><SearchBox value={query} onChange={onQuery} label={`Search ${scope}`} placeholder={scope==='venues'?'Name, neighborhood, cuisine…':'Event, performer, venue, category…'}/><p className="gt-ux-search-help">Search the catalog by keyword. Narrow it with categories{scope==='entertainment'?' and a date':''}.</p><div className="gt-ux-chips" aria-label="Browse categories">{categories.map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div>{scope==='entertainment'&&<label className="gt-ux-date-filter">Date<input type="date" min={cityDate()} value={date} onChange={e=>setDate(e.target.value)}/>{date&&<button onClick={()=>setDate('')}>Any date</button>}</label>}
    <Section kicker={scope==='venues'?'PLACES & ENTITIES':'THINGS TO DO'} title={query?`Results for “${query}”`:category?categories.find(([id])=>id===category)?.[1]:'Explore the city'}><div className="gt-ux-directory-grid">{items.map(item=><UXCard key={item.event_key||item.id} item={item} type={scope==='venues'?'venue':'event'} saved={savedKeys.has(`${scope==='venues'?'venue':'event'}:${item.event_key||item.id}`)} onOpen={scope==='venues'?onVenue:onEvent} onSave={onSave}/>)}</div>{loading&&<p className="gt-ux-status" role="status">Searching current listings…</p>}{error&&<div className="gt-ux-message" role="alert"><p>{error}</p><button onClick={()=>setAttempt(x=>x+1)}>Retry search</button></div>}{!loading&&!error&&!items.length&&<div className="gt-ux-message"><h3>No matching listings in this page.</h3><p>Try a broader keyword or remove a filter. Categories reflect verified records, not guessed amenities.</p><button onClick={()=>{setCategory('');setDate('');onQuery('')}}>Clear search and filters</button></div>}{more&&!error&&<button className="gt-ux-loadmore" disabled={loading} onClick={()=>setPage(x=>x+1)}>{loading?'Loading…':'Load more results'}</button>}</Section>
  </section>
}
export function ProfileLibrary({plans,saved,events,venues,savedKeys,onPlanOpen,onCreate,onEvent,onVenue,onSave}) {
  const[view,setView]=useState('plans'),[bucket,setBucket]=useState('upcoming')
  const buckets={upcoming:plans.filter(p=>planBucket(p)==='upcoming'),drafts:plans.filter(p=>planBucket(p)==='drafts'),past:plans.filter(p=>planBucket(p)==='past')}
  const selected=buckets[bucket],savedEvents=events.filter(e=>savedKeys.has(`event:${e.event_key}`)),savedVenues=venues.filter(v=>savedKeys.has(`venue:${v.id}`))
  return <section className="gt-ux-library" aria-label="My plans and saved items"><div className="gt-ux-library-tabs"><button aria-pressed={view==='plans'} onClick={()=>setView('plans')}>My Plans <span>{plans.length}</span></button><button aria-pressed={view==='saved'} onClick={()=>setView('saved')}>Saved <span>{saved.length}</span></button></div>{view==='plans'?<><div className="gt-ux-chips">{[['upcoming','Upcoming'],['drafts','Drafts'],['past','Past']].map(([id,label])=><button key={id} aria-pressed={bucket===id} onClick={()=>setBucket(id)}>{label} {buckets[id].length}</button>)}</div><div className="gt-ux-my-plans">{selected.map(plan=><button key={plan.id} onClick={()=>onPlanOpen(plan)}><span>{String(plan.status||'draft').toUpperCase()}</span><h3>{plan.name||'My GOOD TIMES plan'}</h3><p>{dateLabel(plan.itinerary_date)} · {(plan.stops||[]).length} stops</p><strong>Open plan →</strong></button>)}</div>{!selected.length&&<div className="gt-ux-message"><h3>{bucket==='drafts'?'Room for your next idea.':bucket==='past'?'Your good times will live here.':'Something to look forward to.'}</h3><p>{bucket==='upcoming'&&buckets.drafts.length?`You have ${buckets.drafts.length} draft plan${buckets.drafts.length===1?'':'s'} ready to review.`:'Create a plan with Click, Shake or Ask.'}</p><button className="primary" onClick={onCreate}>Create a plan →</button></div>}</>:<><div className="gt-ux-rows">{savedEvents.map(event=><UXCard key={event.event_key} compact item={event} type="event" saved onOpen={onEvent} onSave={onSave}/>)}{savedVenues.map(venue=><UXCard key={venue.id} compact item={venue} type="venue" saved onOpen={onVenue} onSave={onSave}/>)}</div>{!saved.length&&<p className="gt-ux-note">Save an event or place anywhere in GOOD TIMES. It will stay here.</p>}{saved.length>savedEvents.length+savedVenues.length&&<p className="gt-ux-note">Some saved items are outside the current loaded inventory. Your saved records have not been removed.</p>}</>}</section>
}
