import {createClient} from 'npm:@supabase/supabase-js@2.110.2';
import {parsePage,identity,safeURL} from './scout-core.mjs';
import {htmlEvents} from './html-adapters.mjs';
const db=createClient(Deno.env.get('SUPABASE_URL')!,(JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS') ?? '{}')['default'] ?? Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'))!,{auth:{persistSession:false}});
const workers=['GT_ATL_MARQUEE_SCOUT','GT_ATL_CONCERT_SCOUT','GT_ATL_COMEDY_SCOUT','GT_ATL_PARTY_SCOUT'];
const j=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function checked(q:any){const r=await q;if(r.error)throw new Error(r.error.message);return r.data}
const errorMessage=(error:unknown)=>String(error&&typeof error==='object'&&'message' in error?error.message||error:error);
const host=(s:string)=>new URL(s).hostname.replace(/^www\./,'');
async function rawFetch(url:string,hosts:string[],limit=2000000){let target=url;for(let hop=0;hop<4;hop++){if(!safeURL(target)||!hosts.includes(host(target)))throw new Error('unapproved_fetch_host');const r=await fetch(target,{redirect:'manual',signal:AbortSignal.timeout(10000),headers:{'user-agent':'GoodTimesAtlantaSourceBot/2.0 (+https://thegoodtimesworldwide.com)','accept':'text/html,application/ld+json,text/plain;q=0.8'}});if([301,302,303,307,308].includes(r.status)){target=new URL(r.headers.get('location')||'',target).href;continue}if(!r.ok)throw new Error('http_'+r.status);if(Number(r.headers.get('content-length')||0)>limit)throw new Error('body_too_large');const reader=r.body?.getReader();if(!reader)throw new Error('empty_body');let total=0;const chunks=[];while(true){const p=await reader.read();if(p.done)break;total+=p.value.length;if(total>limit){await reader.cancel();throw new Error('body_too_large')}chunks.push(p.value)}const all=new Uint8Array(total);let pos=0;for(const c of chunks){all.set(c,pos);pos+=c.length}return{url:target,text:new TextDecoder().decode(all)}}throw new Error('redirect_limit')}
const robotsCache=new Map<string,string>();
async function fetchPage(url:string,hosts:string[]){const origin=new URL(url).origin;let robots=robotsCache.get(origin);if(robots===undefined){try{robots=(await rawFetch(origin+'/robots.txt',hosts,200000)).text}catch(e){if(errorMessage(e)==='http_404')robots='';else throw new Error('robots_unavailable_'+errorMessage(e))}robotsCache.set(origin,robots)}let applies=false;const rules:{path:string;allow:boolean}[]=[];for(const row of robots.split('\n')){const [name,...tail]=row.split(':');const value=tail.join(':').split('#')[0].trim();if(name.trim().toLowerCase()==='user-agent')applies=value==='*'||/GoodTimesAtlantaSourceBot/i.test(value);else if(applies&&['allow','disallow'].includes(name.trim().toLowerCase())&&value)rules.push({path:value,allow:name.trim().toLowerCase()==='allow'})}const path=new URL(url).pathname;const matching=rules.filter(x=>{try{return new RegExp('^'+x.path.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*')).test(path)}catch{return path.startsWith(x.path)}}).sort((a,b)=>b.path.length-a.path.length||Number(b.allow)-Number(a.allow));if(matching[0]&&!matching[0].allow)throw new Error('robots_disallowed');return rawFetch(url,hosts)}
async function run(p:any){const start=new Date().toISOString();const source:any=await checked(db.from('gt_event_sources').select('id,source_name,source_url,city').eq('id',p.source_id).single());if(source.city.toLowerCase()!=='atlanta')throw new Error('source_city_mismatch');const policy={...p,source_url:source.source_url};const hosts=[host(source.source_url),...(p.detail_hosts||[])];const events=new Map<string,any>(),links=new Set<string>(),errors:any[]=[],rejections:Record<string,number>={};let pages=0,parseErrors=0,htmlFallbackEvents=0;
const inspect=async(url:string,detail=false)=>{try{const page=await fetchPage(url,hosts);pages++;const extra=htmlEvents(page.text,page.url);htmlFallbackEvents+=extra.length;const enriched=extra.length?page.text+'<script type="application/ld+json">'+JSON.stringify(extra).replace(/</g,'\\u003c')+'</script>':page.text;const data=parsePage(enriched,page.url,policy);parseErrors+=data.parseErrors;for(const e of data.events)events.set(identity(e),e);for(const l of data.links)links.add(l);for(const m of page.text.matchAll(/data-permalink=["']([^"']+)["']/gi)){const link=safeURL(m[1],page.url);if(link&&hosts.includes(host(link)))links.add(link)}for(const reason of data.rejections)rejections[reason]=(rejections[reason]||0)+1;if(detail)await checked(db.from('gt_atlanta_priority_urls_v1').update({state:data.events.length?'parsed':'empty_needs_review',last_checked_at:new Date().toISOString(),attempts:1,last_error:data.events.length?null:'no_current_structured_event'}).eq('source_id',p.source_id).eq('url',url));}catch(e){const reason=errorMessage(e).slice(0,160);errors.push({url,reason});if(detail)await db.from('gt_atlanta_priority_urls_v1').update({state:'failed',last_checked_at:new Date().toISOString(),last_error:reason}).eq('source_id',p.source_id).eq('url',url)}};
await Promise.all([source.source_url,...(p.extra_pages||[]).slice(0,2)].map(u=>inspect(u)));
const urls=[...links].slice(0,150);if(urls.length)await checked(db.from('gt_atlanta_priority_urls_v1').upsert(urls.map(url=>({source_id:p.source_id,url})),{onConflict:'source_id,url',ignoreDuplicates:true}));
const due:any[]=await checked(db.from('gt_atlanta_priority_urls_v1').select('url').eq('source_id',p.source_id).or('last_checked_at.is.null,last_checked_at.lt.'+new Date(Date.now()-p.poll_minutes*60000).toISOString()).order('last_checked_at',{ascending:true,nullsFirst:true}).limit(8));for(let i=0;i<due.length;i+=4)await Promise.all(due.slice(i,i+4).map(x=>inspect(x.url,true)));
const batch=[...events.values()].slice(0,150);let ingested:any={occurrences_processed:0,new_show_candidates:0};if(batch.length)ingested=await checked(db.rpc('gt_ingest_priority_events_v1',{p_source:p.source_id,p_events:batch}));const pending=await db.from('gt_atlanta_priority_urls_v1').select('url',{count:'exact',head:true}).eq('source_id',p.source_id).is('last_checked_at',null);const backlog=pending.count||0;const state=errors.length?(batch.length?'partial':'failed'):batch.length?(backlog?'partial_backlog':'healthy'):'empty_needs_review';const receipt={source_name:source.source_name,worker:p.worker_key,pages_fetched:pages,discovered_detail_urls:urls.length,detail_backlog:backlog,parse_errors:parseErrors,html_fallback_events:htmlFallbackEvents,events_observed:batch.length,publication_candidates:batch.filter(x=>x.publication).length,held:batch.filter(x=>!x.publication).length,rejections,errors,...ingested,geography:'Atlanta market; metro locality preserved; other cities rejected',coverage_scope:'Bounded source traversal; healthy does not certify complete calendar coverage',all_events_public:false};
const now=new Date().toISOString();await checked(db.from('gt_atlanta_priority_policy_v1').update({last_state:state,last_result:receipt,last_success_at:batch.length?now:p.last_success_at,lease_until:null,consecutive_failures:state==='healthy'?0:p.consecutive_failures+1,next_check_at:new Date(Date.now()+(backlog?5:state==='healthy'?p.poll_minutes:30)*60000).toISOString()}).eq('source_id',p.source_id));await checked(db.from('gt_atlanta_priority_runs_v1').insert({worker_key:p.worker_key,source_id:p.source_id,started_at:start,completed_at:now,state,receipt}));await checked(db.from('gt_event_sources').update({last_scraped_at:now,last_scrape_status:state==='healthy'?'success':state,events_found_last_run:batch.length,updated_at:now}).eq('id',p.source_id));return{source_id:p.source_id,state,...receipt};}
Deno.serve(async req=>{if(req.method!=='POST')return j({ok:false,error:'method_not_allowed'},405);try{const c:any=await checked(db.from('credentials').select('credential_value').eq('credential_key','gt_atlanta_source_internal').eq('is_active',true).single());if(!c.credential_value?.api_key||req.headers.get('x-khg-internal-key')!==c.credential_value.api_key)return j({ok:false,error:'unauthorized'},401);const body=await req.json();if(!workers.includes(body.worker))return j({ok:false,error:'worker_not_allowed'},400);const policies:any[]=await checked(db.rpc('gt_claim_priority_sources_v1',{p_worker:body.worker,p_limit:2}));const results=[];for(const p of policies){try{results.push(await run(p))}catch(e){const error=errorMessage(e).slice(0,220);await db.from('gt_atlanta_priority_policy_v1').update({last_state:'failed',last_result:{error},lease_until:null,next_check_at:new Date(Date.now()+30*60000).toISOString(),consecutive_failures:p.consecutive_failures+1}).eq('source_id',p.source_id);results.push({source_id:p.source_id,state:'failed',error})}}return j({ok:results.every(r=>r.state==='healthy'),worker:body.worker,results,completed_at:new Date().toISOString()});}catch(e){return j({ok:false,error:errorMessage(e).slice(0,220)},500)}});

