import test from'node:test'
import assert from'node:assert/strict'
import fs from'node:fs'
import{parseScope,encodeCursor,showToEvent,eventMatches}from'../api/compact-event-query.js'
import{validatePlanInput,generateSuggestedPlan,rankPlanVenues,hoursContain,planWarnings}from'../api/compact-plan-rules.js'
import{safeGame}from'../api/compact-sports.js'
import{calendarFile,qualifiedStatus,safeURL}from'../src/features/experience/compact-display.js'
const now=Date.parse('2026-09-27T20:00:00Z')
const scope=x=>parseScope(new URLSearchParams(x),now)
const input={date:'2026-09-27',start:'19:00',end:'01:00',people:2,vibes:['food']}
const venues=[{id:'dinner',name:'Dinner',category_key:'restaurant',quality_score:90,neighborhood:'Midtown',website:'https://example.test/dinner',hours:{sun:[{open:'18:00',close:'23:00'}]}},{id:'lounge',name:'Lounge',category_key:'lounge',quality_score:80,neighborhood:'Midtown',website:'https://example.test/lounge'},{id:'club',name:'Club',category_key:'nightclub',quality_score:70,neighborhood:'West Midtown',website:'https://example.test/club'}]
const show={id:'11111111-1111-4111-8111-111111111111',event_name:'An artist in concert',city_key:'atlanta',show_date:'2026-09-27',show_time:'21:00',venue_name:'State Farm Arena',ticket_url:'https://example.test/tickets',image_url:'https://example.test/image.jpg',updated_at:'2026-09-27T17:00:00Z',status:'confirmed',category_key_v2:'concerts_live_music',subcategory_key_v2:'arena_shows',event_type:'concert',genre:'hip hop'}
test('complete event read binds category/date/page size and fixes Atlanta',()=>{assert.equal(scope({city:'miami',category:'nightlife',limit:'10000'}).city,'atlanta');assert.equal(scope({limit:'999'}).limit,48);assert.throws(()=>scope({subcategory:'clubs'}));assert.throws(()=>scope({category:'nightlife,or(city.miami)'}))})
test('Tonight before 4am uses current canonical prior service evening',()=>assert.equal(parseScope(new URLSearchParams({mode:'tonight'}),Date.parse('2026-09-28T06:00:00Z')).date,'2026-09-27'))
test('date bounds are real dates and limited',()=>{assert.throws(()=>scope({date:'2026-02-30'}));assert.throws(()=>scope({date:'2026-09-27',to:'2030-09-27'}))})
test('event cursor cannot be reused against a different scope',()=>{const s=scope({category:'nightlife'}),cursor=encodeCursor({...show},s);assert.ok(scope({category:'nightlife',cursor}).after);assert.throws(()=>scope({category:'sports_watch',cursor}))})
test('row freshness is checked per event, not newest row',()=>{assert.ok(showToEvent(show,now));assert.equal(showToEvent({...show,updated_at:'2026-01-01'},now),null)})
test('wrong city, missing tickets, sold out cannot become event recommendations',()=>{assert.equal(showToEvent({...show,city_key:'miami'},now),null);assert.equal(showToEvent({...show,ticket_url:null},now),null);assert.equal(showToEvent({...show,is_sold_out:true},now),null)})
test('music never fills a sports collection',()=>assert.equal(eventMatches(showToEvent(show,now),scope({category:'sports_watch'}),now),false))
test('planner validates group, dates and duration',()=>{assert.throws(()=>validatePlanInput({...input,people:1.5},now));assert.throws(()=>validatePlanInput({...input,date:'2026-08-01'},now));assert.throws(()=>validatePlanInput({...input,start:'01:00',end:'20:00'},now));assert.equal(validatePlanInput(input,now).endMinute,1500)})
test('venue hours do not default to open',()=>{assert.equal(hoursContain(venues[1],input.date,19*60),null);assert.equal(hoursContain(venues[0],input.date,19*60),true);assert.equal(hoursContain(venues[0],input.date,23*60),false)})
test('area and must-have requirements are not silently relaxed',()=>{const spec=validatePlanInput({...input,area:'Midtown',needs:['vegan']},now);assert.equal(rankPlanVenues(venues,spec).length,0);assert.throws(()=>generateSuggestedPlan({input:{...input,area:'Unknown area'},venues,events:[],id:'plan',now}),/No suitable/)})
test('generated plan uses canonical identities and suggested states',()=>{const p=generateSuggestedPlan({input,venues,events:[],id:'plan',now});assert.equal(p.stops.length,3);assert.ok(p.stops.every(s=>s.status==='SUGGESTED'&&s.id.startsWith('venue:')));assert.equal(p.metadata.timing_verified,false);assert.ok(p.metadata.warnings.some(x=>x.includes('Travel')))})
test('unknown event end does not acquire an invented late-night stop',()=>{const event=showToEvent(show,now);const p=generateSuggestedPlan({input:{...input,vibes:['live']},venues,events:[event],id:'plan',now});assert.equal(p.stops.at(-1).type,'event');assert.ok(p.metadata.warnings.some(x=>x.includes('end time')))})
test('pinned place cannot be substituted silently',()=>assert.throws(()=>generateSuggestedPlan({input:{...input,pinned:'unknown'},venues,events:[],id:'plan',now}),/no longer meets/))
test('impossible pinned event is not silently replaced',()=>assert.throws(()=>generateSuggestedPlan({input:{...input,event:'show:unknown'},venues,events:[],id:'plan',now}),/selected event/))
test('reordering exposes inconsistent times',()=>assert.ok(planWarnings([{name:'A',date:input.date,time:'21:00'},{name:'B',date:input.date,time:'19:00'}]).some(w=>w.includes('chronological'))))
test('unbacked confirmations remain suggestions',()=>{assert.equal(qualifiedStatus({status:'CONFIRMED'}),'SUGGESTED');assert.equal(qualifiedStatus({status:'TICKETED'}),'SUGGESTED')})
test('calendar exports actual chosen start, not invented end',()=>{const cal=calendarFile({id:'test',itinerary_date:input.date,stops:[{name:'A',date:input.date,time:'21:00'}]});assert.match(cal,/TZID=America\/New_York:20260927T210000/);assert.doesNotMatch(cal,/DTEND|CONFIRMED/);assert.ok(cal.endsWith('\r\n'))})
test('external actions reject javascript schemes',()=>{assert.equal(safeURL('javascript:alert(1)'),null);assert.equal(safeURL('https://example.test/'),'https://example.test/')})
test('stale sport snapshots cannot be live',()=>{const base={city_key:'atlanta',updated_at:'2026-09-27T19:59:45Z',status:'live',home_score:4,away_score:2};assert.equal(safeGame(base,now).status,'live');assert.equal(safeGame({...base,updated_at:'2026-09-22T00:00:00Z'},now),null);assert.equal(safeGame({...base,updated_at:'2026-09-27T19:50:00Z'},now).home_score,null)})
test('complete planner uses customer auth and account policies, never a service key',()=>{const code=fs.readFileSync('api/compact-plan.js','utf8')+fs.readFileSync('api/compact-content.js','utf8');assert.match(code,/currentUser\(req\)/);assert.match(code,/user_id=eq\.\$\{user.id\}/);assert.doesNotMatch(code,/SERVICE_ROLE|service_role|createClient/);assert.match(code,/updated_at=eq/);assert.match(code,/status:'SUGGESTED'/)})
test('new event page retains invoker security and canonical editorial eligibility',()=>{const sql=fs.readFileSync('supabase/migrations/20260927210000_gt_compact_event_page_v1.sql','utf8');assert.match(sql,/security invoker/);assert.match(sql,/gt_atlanta_editorial_selection_v1/);assert.match(sql,/72 hours/);assert.doesNotMatch(sql,/security definer|cron\./)})
test('complete path keeps original nav and removes old shortcut strips by variant',()=>{const code=fs.readFileSync('src/features/experience/GoodTimesCommandAppV4.jsx','utf8'),home=fs.readFileSync('src/features/experience/CompactHome.jsx','utf8');assert.match(code,/CompactHome/);assert.match(code,/CompactItinerary/);assert.doesNotMatch(home,/gt5-home-quick|gt5-intents/);assert.match(code,/Home'\],\['discover'.*Discover'\],\['plan'.*Plan'\],\['saved'.*Saved'\],\['profile'.*Profile'/)})
