import test from 'node:test'
import assert from 'node:assert/strict'
import {dateNumber,timeMinutes,selectedCityClock,eventIsTonight,eventIsToday,eventIsThisWeekend,eventDaysAway,eventStatus} from '../src/features/experience/good-times-event-clock.js'
const MON='2026-09-14T12:00:00Z'
const ev=(date='2026-09-14',time='20:00',extra={})=>({city_key:'atlanta',event_date:date,event_time:time,...extra})
const checks=[
 ['morning event is TODAY, not TONIGHT',()=>assert.equal(eventStatus(ev(undefined,'09:00'),'atlanta',MON),'TODAY')],
 ['unknown event time is not TONIGHT',()=>assert.equal(eventIsTonight(ev(undefined,null),'atlanta',MON),false)],
 ['evening is tonight',()=>assert.equal(eventStatus(ev(),'atlanta',MON),'TONIGHT')],
 ['18:00 night boundary included',()=>assert.equal(eventIsTonight(ev(undefined,'18:00'),'atlanta',MON),true)],
 ['17:59 without an end is not tonight',()=>assert.equal(eventIsTonight(ev(undefined,'17:59'),'atlanta',MON),false)],
 ['verified daytime event crossing night is included',()=>assert.equal(eventIsTonight(ev(undefined,'16:00',{end_time:'20:00'}),'atlanta',MON),true)],
 ['Tuesday is not This Weekend from Monday',()=>assert.equal(eventIsThisWeekend(ev('2026-09-15'),'atlanta',MON),false)],
 ['next Monday is not This Weekend',()=>assert.equal(eventIsThisWeekend(ev('2026-09-21'),'atlanta',MON),false)],
 ['Friday is This Weekend',()=>assert.equal(eventIsThisWeekend(ev('2026-09-18'),'atlanta',MON),true)],
 ['Saturday is This Weekend',()=>assert.equal(eventIsThisWeekend(ev('2026-09-19'),'atlanta',MON),true)],
 ['Sunday is This Weekend',()=>assert.equal(eventIsThisWeekend(ev('2026-09-20'),'atlanta',MON),true)],
 ['last Sunday is not upcoming',()=>assert.equal(eventIsThisWeekend(ev('2026-09-13'),'atlanta',MON),false)],
 ['Saturday does not select already elapsed Friday',()=>assert.equal(eventIsThisWeekend(ev('2026-09-18'),'atlanta','2026-09-19T16:00:00Z'),false)],
 ['Sunday selects current Sunday',()=>assert.equal(eventIsThisWeekend(ev('2026-09-20'),'atlanta','2026-09-20T16:00:00Z'),true)],
 ['Sunday does not advance to next Friday',()=>assert.equal(eventIsThisWeekend(ev('2026-09-25'),'atlanta','2026-09-20T16:00:00Z'),false)],
 ['next-day 03:00 belongs to scheduled night',()=>assert.equal(eventIsTonight(ev('2026-09-15','03:00'),'atlanta','2026-09-15T01:00:00Z'),true)],
 ['next-day 04:00 does not belong to prior night',()=>assert.equal(eventIsTonight(ev('2026-09-15','04:00'),'atlanta','2026-09-15T01:00:00Z'),false)],
 ['overnight continuation requires a documented end',()=>assert.equal(eventIsTonight(ev('2026-09-14','22:00'),'atlanta','2026-09-15T05:00:00Z'),false)],
 ['known overnight end retains relevant event',()=>assert.equal(eventIsTonight(ev('2026-09-14','22:00',{end_time:'03:00'}),'atlanta','2026-09-15T05:00:00Z'),true)],
 ['ended overnight event is not tonight',()=>assert.equal(eventIsTonight(ev('2026-09-14','22:00',{end_time:'00:30'}),'atlanta','2026-09-15T05:00:00Z'),false)],
 ['known ended event has truthful ENDED badge',()=>assert.equal(eventStatus(ev(undefined,'18:00',{end_time:'20:00'}),'atlanta','2026-09-15T01:00:00Z'),'ENDED')],
 ['Monday 01:00 retains verified Sunday night weekend',()=>assert.equal(eventIsThisWeekend(ev('2026-09-20','22:00',{end_time:'03:00'}),'atlanta','2026-09-21T05:00:00Z'),true)],
 ['Monday 04:00 starts new service date',()=>assert.equal(selectedCityClock('atlanta','2026-09-21T08:00:00Z').serviceDate,'2026-09-21')],
 ['wrong-city tonight suppressed',()=>assert.equal(eventIsTonight(ev(),'miami',MON),false)],
 ['wrong-city weekend suppressed',()=>assert.equal(eventIsThisWeekend(ev('2026-09-18'),'las_vegas',MON),false)],
 ['unsupported city cannot inherit device zone',()=>assert.equal(selectedCityClock('unknown',MON),null)],
 ['Vegas clock differs from Atlanta at same instant',()=>assert.equal(selectedCityClock('las_vegas','2026-09-15T02:00:00Z').date,'2026-09-14')],
 ['Vegas tonight uses local calendar',()=>assert.equal(eventIsTonight(ev('2026-09-14','22:00',{city_key:'las_vegas'}),'las_vegas','2026-09-15T02:00:00Z'),true)],
 ['New York alias resolves',()=>assert.equal(selectedCityClock('NYC',MON).city,'new_york')],
 ['city date distance is independent of host',()=>assert.equal(eventDaysAway('2026-09-14','las_vegas','2026-09-15T02:00:00Z'),0)],
 ['spring DST does not move weekend date',()=>assert.equal(eventIsThisWeekend(ev('2027-03-14'),'atlanta','2027-03-12T14:00:00Z'),true)],
 ['fall DST does not move weekend date',()=>assert.equal(eventIsThisWeekend(ev('2026-11-01'),'atlanta','2026-10-30T14:00:00Z'),true)],
 ['leap day validated',()=>assert.ok(dateNumber('2028-02-29')!==null)],
 ['nonleap day rejected',()=>assert.equal(dateNumber('2026-02-29'),null)],
 ['24-hour overflow rejected',()=>assert.equal(timeMinutes('24:00'),null)],
 ['bad minutes rejected',()=>assert.equal(timeMinutes('20:75'),null)],
 ['time-zone-bearing local time not guessed',()=>assert.equal(timeMinutes('20:00+00:00'),null)],
 ['seconds supported',()=>assert.equal(timeMinutes('20:45:00'),1245)],
 ['bad end-date cannot attest tonight',()=>assert.equal(eventIsTonight(ev(undefined,'20:00',{end_date:'2026-02-30',end_time:'23:00'}),'atlanta',MON),false)],
 ['cancelled status retained',()=>assert.equal(eventStatus(ev(undefined,'20:00',{status:'cancelled'}),'atlanta',MON),'CANCELLED')],
 ['sold out is not actionable tonight',()=>assert.equal(eventIsTonight(ev(undefined,'20:00',{ticket_status:'sold_out'}),'atlanta',MON),false)],
 ['postponed event suppressed',()=>assert.equal(eventIsThisWeekend(ev('2026-09-18','20:00',{status:'postponed'}),'atlanta',MON),false)],
 ['presale status retained',()=>assert.equal(eventStatus(ev('2026-09-18','20:00',{ticket_status:'presale'}),'atlanta',MON),'PRESALE')],
 ['functions do not mutate inventory',()=>{const e=Object.freeze(ev());eventStatus(e,'atlanta',MON);assert.equal(e.event_time,'20:00')}],
 ['no reservation confirmation derived from schedule',()=>assert.notEqual(eventStatus(ev(),'atlanta',MON),'CONFIRMED')],
 ['missing date does not become upcoming weekend',()=>assert.equal(eventIsThisWeekend({...ev(),event_date:null},'atlanta',MON),false)],
 ['TODAY includes daytime without calling it an evening event',()=>assert.equal(eventIsToday(ev(undefined,'12:00'),'atlanta',MON),true)],
]
for(const [name,run] of checks)test(name,run)
