import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import {createHash} from 'node:crypto'
const BASE=process.env.GT_UI_BASE
const OUT=path.join(process.env.GT_UI_ARTIFACTS||'ui-artifacts','reference-base')
let chromium;try{({chromium}=await import('playwright-core'))}catch{}
const skip=!BASE||!chromium?'requires the rendered UI environment':false
const epoch=Date.parse('2026-09-28T00:30:00-04:00')
const session={access_token:'reference-isolated-test-token',user:{id:'11111111-1111-4111-8111-111111111111'},expires_at:4102444800}
const profile={id:'22222222-2222-4222-8222-222222222222',auth_id:session.user.id,full_name:'Reference QA',home_city:'atlanta',last_city:'atlanta',vibe_preferences:['dining','nightlife']}
const categoryRows=[['dining_culinary','Restaurants'],['nightlife','Nightlife Places'],['entertainment','Entertainment Venues'],['attractions_experiences','Attractions'],['family_kids','Family Places']].map(([category_key,category_name],sort_order)=>({category_key,category_name,sort_order,is_active:true}))
const subRows=categoryRows.map((c,i)=>({category_key:c.category_key,subcategory_key:`${c.category_key}_fixture`,subcategory_name:`${c.category_name} Picks`,sort_order:0,is_active:true}))
const venues=Array.from({length:6},(_,i)=>{const c=categoryRows[i%categoryRows.length],sub=subRows.find(s=>s.category_key===c.category_key);return{id:`3000000${i}-3333-4333-8333-333333333333`,name:`Reference Place ${i+1}`,category_key:c.category_key,venue_category_key:c.category_key,subcategory_key:sub.subcategory_key,subcategory:sub.subcategory_name,venue_subcategory:sub.subcategory_name,city_key:'atlanta',neighborhood:'Midtown',short_desc:'Isolated layout-test record. Not a real venue recommendation.',hero_image:'/venues/revel.webp',quality_score:90-i,price_range:'$$',address:'Reference address — not a booking',website:'https://example.invalid/reference-only',status:'active',is_verified:true,verification_status:'verified_current',freshness_expires_at:'2026-10-28T00:00:00Z',latitude:33.77+i/1000,longitude:-84.39-i/1000}})
const eventCats=['nightlife','concerts_live_music','sports_watch','festivals_major_activations','comedy_performing_arts','games_interactive','family_kids','attractions_experiences']
const events=Array.from({length:8},(_,i)=>({event_key:`show:4000000${i}-4444-4444-8444-444444444444`,id:`4000000${i}-4444-4444-8444-444444444444`,title:`Reference Entertainment ${i+1}`,category_key:eventCats[i],subcategory_key:'fixture',city_key:'atlanta',event_date:'2026-09-28',event_time:`${18+i%5}:00`,venue_id:venues[i%venues.length].id,venue_name:venues[i%venues.length].name,image_url:'/venues/revel.webp',ticket_url:'https://example.invalid/reference-only',quality_score:90-i,is_verified:true,updated_at:'2026-09-28T03:00:00Z'}))
const plan={id:'55555555-5555-4555-8555-555555555555',user_id:session.user.id,name:'Atlanta Night Out',status:'draft',itinerary_date:'2026-09-28',city_id:'atlanta',group_size:2,stops:[{id:'venue:'+venues[0].id,object_id:venues[0].id,type:'venue',name:venues[0].name,time:'19:30',role:'Dinner',address:venues[0].address,image_url:venues[0].hero_image,status:'SUGGESTED',hours_verified:false,travel_verified:false},{id:events[0].event_key,object_id:events[0].id,type:'event',name:events[0].title,time:'21:00',date:'2026-09-28',role:'Main event',venue:events[0].venue_name,image_url:events[0].image_url,status:'SUGGESTED',hours_verified:true,travel_verified:false}]}
const saved=[{id:'save-v',user_id:profile.id,item_type:'venue',item_id:venues[0].id,saved_at:'2026-09-28T02:00:00Z'},{id:'save-e',user_id:profile.id,item_type:'event',item_id:events[0].event_key,saved_at:'2026-09-28T02:00:00Z'}]
const counts=categoryRows.map(c=>({category_key:c.category_key,subcategory_key:null,place_count:venues.filter(v=>v.category_key===c.category_key).length})).concat(subRows.map(s=>({category_key:s.category_key,subcategory_key:s.subcategory_key,place_count:venues.filter(v=>v.subcategory_key===s.subcategory_key).length})))
const json=body=>({status:200,contentType:'application/json',body:JSON.stringify(body)})
for(const viewport of[{width:390,height:844},{width:834,height:1194},{width:1440,height:900}]){
 test(`reference-base nine approved screens ${viewport.width}`,{skip,timeout:120000},async()=>{
  assert.ok(['localhost','127.0.0.1'].includes(new URL(BASE).hostname),'Isolated fixture proof must never write to production')
  const browser=await chromium.launch({executablePath:process.env.GT_UI_CHROME_PATH||undefined,headless:true,args:['--no-sandbox']})
  const context=await browser.newContext({viewport,timezoneId:'America/New_York',reducedMotion:'reduce'})
  const page=await context.newPage(),errors=[],proof=[],dir=path.join(OUT,String(viewport.width));fs.mkdirSync(dir,{recursive:true});page.on('pageerror',e=>errors.push(e.message))
  async function capture(name,scroller='.gt5-main'){const scroll=page.locator(scroller).last();if(await scroll.count())await scroll.evaluate(e=>{e.scrollTop=0});await page.waitForTimeout(120);const report=await page.evaluate(()=>({horizontalOverflow:document.documentElement.scrollWidth-innerWidth,screen:document.querySelector('.gt5-app')?.dataset.screen}));assert.ok(report.horizontalOverflow<=1,`${name} overflow ${report.horizontalOverflow}`);for(const position of['top','bottom']){if(position==='bottom'&&await scroll.count())await scroll.evaluate(e=>{e.scrollTop=e.scrollHeight});await page.waitForTimeout(80);const filename=`${name}-${position}.png`,buffer=await page.screenshot({animations:'disabled'});fs.writeFileSync(path.join(dir,filename),buffer);proof.push({screen:name,position,filename,sha256:createHash('sha256').update(buffer).digest('hex'),...report})}if(await scroll.count())await scroll.evaluate(e=>{e.scrollTop=0})}
  const tab=async(label,selector)=>{await page.locator('.gt5-nav button').filter({hasText:new RegExp(`^${label}$`)}).click();await page.locator(selector).waitFor()}
  try{
   await context.addInitScript(({session,epoch})=>{const D=Date;window.Date=class extends D{constructor(...a){super(...(a.length?a:[epoch]))}static now(){return epoch}};localStorage.setItem('gt_session',JSON.stringify(session));sessionStorage.setItem('gt_premium_launch','1');sessionStorage.setItem('gt_splash_shown','1')},{session,epoch})
   await context.route('**/api/**',route=>{const u=new URL(route.request().url()),p=u.pathname;if(p==='/api/health')return route.fulfill(json({ok:true,service:'good-times',customer_ready:true,content_ready:true}));if(p.startsWith('/api/data'))return route.fulfill(json({ok:true,connected:true,degraded:false,city:'atlanta',events,venues}));if(p==='/api/browse'){const kind=u.searchParams.get('kind');if(kind==='venue'){const id=u.searchParams.get('id'),v=venues.find(x=>x.id===id);return route.fulfill(json({ok:true,items:v?[v]:[],nextCursor:null,asOf:new Date(epoch).toISOString()}))}return route.fulfill(json({ok:true,items:events,nextCursor:null,asOf:new Date(epoch).toISOString()}))}if(p==='/api/saved-content')return route.fulfill(json({ok:true,items:[venues[0],events[0]]}));if(p==='/api/sports-live')return route.fulfill(json({ok:true,items:[],nextCursor:null,asOf:new Date(epoch).toISOString()}));return route.fulfill(json({ok:true}))})
   await context.route('**/rest/v1/**',route=>{const u=new URL(route.request().url()),t=u.pathname.split('/').at(-1);if(t==='gt_user_profiles')return route.fulfill(json([profile]));if(t==='gt_saved_items')return route.fulfill(json(saved));if(t==='itineraries')return route.fulfill(json([plan]));if(t==='gt_taxonomy_categories')return route.fulfill(json(categoryRows));if(t==='gt_taxonomy_subcategories')return route.fulfill(json(subRows));if(t==='v_gt_venue_taxonomy_counts')return route.fulfill(json(counts));if(t==='v_gt_venue_taxonomy_directory'){const cat=String(u.searchParams.get('category_key')||'').replace(/^eq\./,'');return route.fulfill(json(venues.filter(v=>!cat||v.category_key===cat)))}return route.fulfill(json([]))})
   await context.route('**/functions/v1/**',route=>route.fulfill(json({ok:true,events,venues,message:'Reference fixture'})))
   await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.locator('.gtc-home .gtc-card').first().waitFor({timeout:15000})
   assert.deepEqual(await page.locator('.gt5-nav button small').allTextContents(),['Home','Discover','Entertainment','Plan','Profile'])
   assert.equal(await page.locator('.gt5-nav button').filter({hasText:'Saved'}).count(),0)
   await capture('01-home')
   await page.locator('.gt5-home-modes').getByRole('button',{name:'Tonight',exact:true}).click();await page.locator('[data-page="02"]').waitFor();await capture('02-tonight')
   await tab('Discover','.gtc-places');assert.equal(await page.locator('.gt-compact-category-grid>button').count(),categoryRows.length);assert.ok((await page.locator('.gt-compact-category-grid>button').first().evaluate(e=>getComputedStyle(e).backgroundImage))!=='none');await capture('03-places')
   await tab('Entertainment','.gtc-entertainment');assert.equal(await page.locator('[aria-label="Entertainment categories"]>button:not(:first-child)').count(),9);await capture('04-entertainment')
   await tab('Plan','[data-page="23"]');await page.getByRole('button',{name:/^Build It/}).click();assert.deepEqual(await page.locator('.gtc-planner>.gtc-tabs button').allTextContents(),['Build My Night','Shake','Ask']);await capture('05-plan')
   if(await page.locator('[data-focused-plan]').count())await page.getByRole('button',{name:'← Plans',exact:true}).click();await tab('Profile','.gt5-profile');await page.getByRole('button',{name:'Library',exact:true}).click();await page.locator('.gtc-my-good-times').waitFor();await capture('06-my-good-times')
   await page.locator('.gtc-my-good-times .gt30-plan-strip').first().waitFor({state:'visible',timeout:5000});await page.locator('.gtc-my-good-times .gt30-plan-strip').first().click();await page.locator('.gtc-itinerary').waitFor();assert.equal(await page.locator('.gtc-stop').count(),2);assert.equal(await page.locator('.gtc-itinerary').getByText(/CONFIRMED/).count(),0,'Suggestions must not acquire confirmation');await capture('07-itinerary','.gtc-overlay');await page.getByRole('button',{name:'Close itinerary'}).click()
   await tab('Discover','.gtc-places');await page.getByRole('button',{name:/Attractions/}).click();await page.locator('[data-gt-subcategory]').first().click();await page.locator('.gt2-venue-grid .gtc-card-open').first().click();await page.locator('.gtc-detail').waitFor();await capture('08-place-detail','.gtc-overlay');await page.getByRole('button',{name:'Back to results'}).click()
   if(await page.locator('[data-focused-plan]').count())await page.getByRole('button',{name:'← Plans',exact:true}).click();await tab('Profile','.gt5-profile');await page.locator('.gt5-bell').click();await page.locator('[data-page="28"]').waitFor();await capture('09-radar');await page.getByRole('button',{name:'← Back',exact:true}).click();assert.equal(await page.locator('.gt5-app').getAttribute('data-screen'),'profile','Radar origin lost')
   assert.deepEqual(errors,[])
   fs.writeFileSync(path.join(dir,'evidence.json'),JSON.stringify({evidenceType:'isolated-render-fixture',notProofOfProductionAuthentication:true,commit:process.env.GITHUB_SHA||null,viewport,errors,screenshots:proof},null,2))
  }catch(error){await page.screenshot({path:path.join(dir,'failure.png')}).catch(()=>{});throw error}
  finally{await context.close();await browser.close()}
 })
}
