import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {chromium} from 'playwright-core';import {install,makeState,venues} from './complete-upgrade-fixtures.mjs';
const BASE=process.env.GT_UI_BASE,OUT=(process.env.GT_UI_ARTIFACTS||'ui-artifacts')+'/extra';fs.mkdirSync(OUT,{recursive:true});
async function setup(){const browser=await chromium.launch({executablePath:process.env.GT_UI_CHROME_PATH,headless:true}),ctx=await browser.newContext({viewport:{width:390,height:844},timezoneId:'America/New_York'}),state=makeState();await install(ctx,state);const page=await ctx.newPage();await page.goto(BASE);await page.locator('.gt5-app').waitFor();return{browser,ctx,page,state}}
const nav=(p,n)=>p.locator('.gt5-nav button').filter({hasText:new RegExp('^'+n+'$')}).click();
test('four mood selections, lead choice and draft survive seven-step edit and reload',{skip:!BASE,timeout:60000},async()=>{const{browser,page}=await setup();try{await nav(page,'Plan');await page.getByRole('button',{name:/^Build It/}).click();await page.locator('.gtc-progress button').nth(1).click();await page.getByRole('button',{name:'Friends',exact:true}).click();await page.locator('.gtc-progress button').nth(2).click();for(const mood of ['Chill','Date night','Good food'])await page.locator('.gtc-mood-grid button').filter({hasText:mood}).click();assert.equal(await page.locator('.gtc-mood-grid [aria-pressed="true"]').count(),4);await page.getByLabel('Lead vibe').selectOption('food');await page.locator('.gtc-progress button').nth(6).click();assert.match(await page.locator('.gtc-review').innerText(),/Good food.*Turn up.*Chill.*Date night/s);assert.match(await page.locator('.gtc-review').innerText(),/4 people/);await page.screenshot({path:OUT+'/four-moods-review.png'});await page.reload();await page.locator('.gt5-app').waitFor();await nav(page,'Plan');await page.getByRole('button',{name:/Continue your draft/}).click();await page.locator('.gtc-progress button').nth(2).click();assert.equal(await page.locator('.gtc-mood-grid [aria-pressed="true"]').count(),4);assert.equal(await page.getByLabel('Lead vibe').inputValue(),'food');await page.locator('.gtc-progress button').nth(1).click();assert.equal(await page.getByLabel('How many people?').inputValue(),'4')}finally{await browser.close()}})
test('filtered map options and selected pin retain directory identities',{skip:!BASE,timeout:60000},async()=>{const{browser,page}=await setup();try{await nav(page,'Places');await page.getByRole('navigation',{name:'Place shortcuts'}).getByRole('button',{name:'Nightlife',exact:true}).click();await page.locator('[data-gt-subcategories="nightlife"] button').first().click();await page.locator('.gt2-venue-grid .gtc-card').first().waitFor();const names=await page.locator('.gt2-venue-grid h3').allTextContents();await page.getByRole('button',{name:'Map',exact:true}).first().click();await page.locator('.gt30-map').waitFor();const mapped=(await page.locator('[aria-label="Select map place"] button').allTextContents()).map(x=>x.replace(/^\d+\. /,''));assert.deepEqual([...mapped].sort(),[...names].sort());await page.locator('[aria-label="Select map place"] button').nth(1).click();const expected=venues.find(v=>v.name===mapped[1]);const url=new URL(await page.locator('iframe[title="Atlanta places map"]').getAttribute('src'));assert.equal(url.searchParams.get('marker'),`${expected.latitude},${expected.longitude}`);await page.screenshot({path:OUT+'/map-identity.png'})}finally{await browser.close()}})
test('fixture plan save twice reload and pinned edit maintain one owned record',{skip:!BASE,timeout:60000},async()=>{const{browser,page,state}=await setup();try{await nav(page,'Plan');await page.getByRole('button',{name:/^Build It/}).click();await page.locator('.gtc-progress button').nth(5).click();await page.getByLabel('Everyone is 21 or older').check();await page.locator('.gtc-progress button').nth(6).click();await page.getByRole('button',{name:'Build my plan',exact:true}).click();await page.locator('.gtc-itinerary').waitFor();await page.getByRole('button',{name:'Pin stop',exact:true}).first().click();await page.locator('.gtc-stop-edit summary').first().click();assert.equal(await page.locator('.gtc-stop').first().getByRole('button',{name:'Remove',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Save plan',exact:true}).click();await page.getByRole('button',{name:'Save changes',exact:true}).waitFor();await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('Plan saved.',{exact:true}).first().waitFor();assert.equal(state.plans.length,1);assert.equal(state.plans[0].stops[0].locked,true);await page.reload();await page.locator('.gt5-app').waitFor();await nav(page,'Plan');await page.getByRole('button',{name:/Your Atlanta night/}).click();await page.locator('.gtc-itinerary').waitFor();assert.equal(await page.getByRole('button',{name:'Unpin stop',exact:true}).count(),1);await page.screenshot({path:OUT+'/saved-reloaded-fixture.png'})}finally{await browser.close()}})

test('Ask follow-up preserves constraints through options and Build review',{skip:!BASE,timeout:60000},async()=>{
 const{browser,page,ctx}=await setup();const requests=[]
 await ctx.route('**/functions/v1/**',async route=>{requests.push(JSON.parse(route.request().postData()||'{}'));await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,events:[],venues:[],message:'Controlled follow-up response.'})})})
 try{await nav(page,'Plan');await page.getByRole('button',{name:/^Ask GOOD TIMES/}).click();await page.getByLabel('Ask GOOD TIMES',{exact:true}).fill('Dinner and live music for four people in Midtown, 7 PM to 1 AM');await page.getByRole('button',{name:'Find my options',exact:true}).click();await page.getByText('Controlled follow-up response.',{exact:true}).waitFor();await page.getByLabel('Ask GOOD TIMES',{exact:true}).fill('finish earlier at 11 PM, no clubs');await page.getByRole('button',{name:'Find my options',exact:true}).click();await page.getByText('Controlled follow-up response.',{exact:true}).waitFor();assert.equal(requests.length,2);const body=JSON.stringify(requests[1]);assert.match(body,/Midtown/);assert.match(body,/23:00/);assert.match(body,/food/);assert.match(body,/music/);await page.getByRole('button',{name:'Use this idea to build a plan',exact:true}).click();const review=await page.locator('.gtc-review').innerText();assert.match(review,/4 people/);assert.match(review,/Midtown/);assert.match(review,/No clubs/);assert.match(review,/11:00 PM/);await page.screenshot({path:OUT+'/ask-refinement-review.png'})}finally{await browser.close()}
})

test('itinerary calendar download and share outcomes are truthful',{skip:!BASE,timeout:60000},async()=>{
 const{browser,page,ctx}=await setup();await ctx.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:undefined,configurable:true});Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true})})
 try{await page.reload();await page.locator('.gt5-app').waitFor();await nav(page,'Plan');await page.getByRole('button',{name:/^Build It/}).click();await page.locator('.gtc-progress button').nth(5).click();await page.getByLabel('Everyone is 21 or older').check();await page.locator('.gtc-progress button').nth(6).click();await page.getByRole('button',{name:'Build my plan',exact:true}).click();await page.locator('.gtc-itinerary').waitFor();const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Add to calendar',exact:true}).click();const file=await downloaded;await file.saveAs(OUT+'/fixture-plan.ics');const calendar=fs.readFileSync(OUT+'/fixture-plan.ics','utf8');assert.match(calendar,/BEGIN:VCALENDAR/);assert.match(calendar,/not a reservation/);assert.equal((calendar.match(/BEGIN:VEVENT/g)||[]).length,await page.locator('.gtc-stop').count());await page.getByRole('button',{name:'Share details',exact:true}).click();await page.getByText('Sharing was cancelled or unavailable.',{exact:true}).waitFor();await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.sharedPlan=text}},configurable:true}));await page.getByRole('button',{name:'Share details',exact:true}).click();await page.getByText('Plan details shared. No private link was published.',{exact:true}).waitFor();assert.match(await page.evaluate(()=>window.sharedPlan),/Opium|Revel|Utopia|Magic City|Vision/);for(const link of await page.locator('.gtc-stop-links a').all()){const href=await link.getAttribute('href');assert.match(href,/^https:\/\//);assert.match(await link.getAttribute('rel'),/noopener/)}await page.screenshot({path:OUT+'/calendar-share.png'})}finally{await browser.close()}
})

test('Sports loads provider games, scopes dates/leagues and exposes partial failures',{skip:!BASE,timeout:60000},async()=>{
 const{browser,page,ctx}=await setup();const requests=[];let failure=false
 await ctx.route('**/api/sports-live?**',async route=>{const u=new URL(route.request().url());requests.push(Object.fromEntries(u.searchParams));const league=u.searchParams.get('league');await route.fulfill({status:failure?503:200,contentType:'application/json',body:JSON.stringify(failure?{ok:false,error:'Provider unavailable'}:{ok:true,items:league==='NBA'?[]:[{id:'fixture-game',league:'NFL',home_team:'Atlanta Falcons',away_team:'New Orleans Saints',home_abbr:'ATL',away_abbr:'NO',is_home_game:true,game_date:u.searchParams.get('date'),game_time:'16:00',status:'live',home_score:0,away_score:7,score_is_provider_reported:true,source_url:'https://www.espn.com/nfl/game/_/gameId/fixture',venue:'Fixture stadium'}],partial:league==='NBA',notice:league==='NBA'?'NBA could not refresh. Other available leagues remain visible.':null,asOf:'2026-09-27T20:00:00Z'})})})
 try{await page.getByRole('button',{name:'Sports',exact:true}).first().click();await page.locator('.gtc-matchup').waitFor();assert.equal(requests.at(-1).date,'2026-09-27');assert.match(await page.getByLabel('Provider-reported score').innerText(),/ATL 0.*NO 7/);assert.equal(await page.getByRole('link',{name:'View provider game ↗'}).getAttribute('href'),'https://www.espn.com/nfl/game/_/gameId/fixture');await page.getByLabel('Game date',{exact:true}).fill('2026-09-28');await page.waitForResponse(r=>r.url().includes('/api/sports-live?')&&r.url().includes('2026-09-28'));await page.locator('.gtc-matchup').waitFor();await page.getByRole('button',{name:'NBA',exact:true}).click();await page.getByText('Some schedules are unavailable',{exact:true}).waitFor();assert.equal(await page.getByLabel('Provider-reported score').count(),0);assert.equal(requests.at(-1).league,'NBA');failure=true;await page.getByRole('button',{name:'Refresh games',exact:true}).click();await page.getByText('Schedules could not refresh',{exact:true}).waitFor();assert.equal(await page.getByText('No games on this date',{exact:true}).count(),0);failure=false;await page.getByRole('button',{name:'Retry',exact:true}).click();await page.getByText('Some schedules are unavailable',{exact:true}).waitFor();await page.screenshot({path:OUT+'/sports-partial-retry.png'})}finally{await browser.close()}
})
