-- Register the existing GOOD TIMES background pack as approved customer UI creative.
-- Applied to canonical content project dzlmtvodpyhetvektfuo on 2026-08-10 UTC.

insert into public.gt_asset_manifest(asset_key,asset_type,surface,category_key,storage_bucket,storage_path,is_active,approved,priority,metadata)
values
('gt-explore-nightlife','category_image','explore_category','nightlife','good-times-backgrounds','gt-cat-nightlife.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-concerts','category_image','explore_category','concerts_live_music','good-times-backgrounds','gt-cat-music.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-festivals','category_image','explore_category','festivals_major_activations','good-times-backgrounds','event-dogwood-festival.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-comedy','category_image','explore_category','comedy_performing_arts','good-times-backgrounds','event-comedy-show.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-culture','category_image','explore_category','arts_museums_culture','good-times-backgrounds','gt-cat-culture.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-dining','category_image','explore_category','dining_culinary','good-times-backgrounds','gt-cat-dining.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-sports','category_image','explore_category','sports_watch','good-times-backgrounds','gt-cat-sports.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-day-party','category_image','explore_category','day_parties_brunch','good-times-backgrounds','event-rooftop-party.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-family','category_image','explore_category','family_kids','good-times-backgrounds','gt-cat-family.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-community','category_image','explore_category','community_civic','good-times-backgrounds','event-streets-alive.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-shopping','category_image','explore_category','fashion_beauty_shopping','good-times-backgrounds','gt-cat-shopping.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-wellness','category_image','explore_category','wellness_fitness','good-times-backgrounds','gt-cat-wellness.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-college','category_image','explore_category','college_alumni','good-times-backgrounds','event-404-day.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-faith','category_image','explore_category','faith_inspirational','good-times-backgrounds','gt-bg-grand-venue.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-dating','category_image','explore_category','dating_social','good-times-backgrounds','gt-cat-dating.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-free','category_image','explore_category','free_things_to_do','good-times-backgrounds','gt-bg-panoramic-skyline.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-vip','category_image','explore_category','vip_exclusive','good-times-backgrounds','gt-cat-exclusive.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-attractions','category_image','explore_category','attractions_experiences','good-times-backgrounds','gt-cat-adventure.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-business','category_image','explore_category','business_professional','good-times-backgrounds','gt-bg-future-city.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-classes','category_image','explore_category','classes_workshops','good-times-backgrounds','mood-explore.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-creator','category_image','explore_category','creative_creator','good-times-backgrounds','event-film-festival.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-games','category_image','explore_category','games_interactive','good-times-backgrounds','event-2000s-party.jpg',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-travel','category_image','explore_category','travel_staycations','good-times-backgrounds','gt-bg-waterfront-venue.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-black-culture','category_image','explore_category','black_culture_diaspora','good-times-backgrounds','gt-bg-social-scene.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-explore-seasonal','category_image','explore_category','seasonal_holiday','good-times-backgrounds','gt-bg-courtyard-evening.webp',true,true,10,'{"role":"explore category art"}'::jsonb),
('gt-build-grown','category_image','build_mood','grown_sexy','good-times-backgrounds','gt-cat-mood-bougie.webp',true,true,12,'{"label":"Grown & sexy"}'::jsonb),
('gt-build-turnt','category_image','build_mood','high_energy','good-times-backgrounds','gt-cat-mood-turnt.webp',true,true,12,'{"label":"High energy"}'::jsonb),
('gt-build-date','category_image','build_mood','date_night','good-times-backgrounds','gt-cat-mood-date.webp',true,true,12,'{"label":"Date night"}'::jsonb),
('gt-build-live','category_image','build_mood','live_music','good-times-backgrounds','gt-cat-music.webp',true,true,12,'{"label":"Live music"}'::jsonb),
('gt-build-black-owned','category_image','build_mood','black_owned','good-times-backgrounds','gt-cat-culture.webp',true,true,12,'{"label":"Black-owned"}'::jsonb),
('gt-build-rooftop','category_image','build_mood','rooftop','good-times-backgrounds','gt-bg-rooftop-lounge.webp',true,true,12,'{"label":"Rooftop"}'::jsonb),
('gt-build-food','category_image','build_mood','food_first','good-times-backgrounds','gt-cat-dining.webp',true,true,12,'{"label":"Food first"}'::jsonb),
('gt-build-different','category_image','build_mood','something_different','good-times-backgrounds','gt-cat-mood-explore.webp',true,true,12,'{"label":"Something different"}'::jsonb),
('gt-nav-now','category_image','navigation','now','good-times-backgrounds','nav-icon-now.webp',true,true,15,'{}'::jsonb),
('gt-nav-dates','category_image','navigation','dates','good-times-backgrounds','nav-icon-dates.webp',true,true,15,'{}'::jsonb),
('gt-nav-build','category_image','navigation','build_my_night','good-times-backgrounds','nav-icon-build-my-night.webp',true,true,15,'{}'::jsonb),
('gt-nav-plans','category_image','navigation','plans','good-times-backgrounds','nav-icon-itinerary.webp',true,true,15,'{}'::jsonb),
('gt-nav-explore','category_image','navigation','explore','good-times-backgrounds','nav-icon-explore.webp',true,true,15,'{}'::jsonb),
('gt-nav-vault','category_image','navigation','vault','good-times-backgrounds','nav-icon-vault.webp',true,true,15,'{}'::jsonb)
on conflict(asset_key) do update set
  asset_type=excluded.asset_type,
  surface=excluded.surface,
  category_key=excluded.category_key,
  storage_bucket=excluded.storage_bucket,
  storage_path=excluded.storage_path,
  is_active=true,
  approved=true,
  priority=excluded.priority,
  metadata=excluded.metadata,
  updated_at=now();
