import {CompactRail} from './DiscoveryPages.jsx'
import React,{useEffect,useRef,useState} from 'react'
import {Picture,State,ActionLink,Section} from './Cards.jsx'
import {EventCollection,CollectionGrid} from './Collections.jsx'
import {list,safeLink,safeImage,displayDate,displayTime,labelFor,identity,cleanTitle} from './model.js'
import {restaurantFactRows} from './restaurant-facts.js'
import {restaurantActionLabel} from './restaurant-actions.js'
import {useBrowse} from './useBrowse.js'
import {shareContent} from '../../../native.js'
export function useDialogFocus(ref,onClose){const close=useRef(onClose);close.current=onClose;useEffect(()=>{const prev=document.activeElement,root=ref.current;if(!root)return;const blocked=[...document.querySelectorAll('.gt5-main,.gt5-nav,.gt5-topbar')];for(const x of blocked)x.inert=true;const focusables=()=>[...root.querySelectorAll('button:not(:disabled),a[href],input,select,textarea,summary,[tabindex="0"]')].filter(x=>x.getClientRects().length);focusables()[0]?.focus();const listener=e=>{if(e.key==='Escape')close.current?.();if(e.key==='Tab'){const items=focusables(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};root.addEventListener('keydown',listener);return()=>{for(const x of blocked)x.inert=false;root.removeEventListener('keydown',listener);prev?.focus?.()}},[])}
export default function Details({item,kind,onClose,onSave,saved,onPlan,onFollow,following,onEvent,savedKeys,saveItem,onVenue,onExplore,now}){
 const ref=useRef(null);useDialogFocus(ref,onClose)
 const event=kind==='event',[tab,setTab]=useState('overview'),[photo,setPhoto]=useState(0),[notice,setNotice]=useState('')
 const live=useBrowse({kind:event?'events':'venue',id:event?item.event_key:item.id},!!(item.event_key||item.id)),venue=live.items[0],record=venue?{...item,...venue}:item
 const unavailable=live.status==='success'&&!venue,blocked=unavailable||/cancelled|canceled|postponed|closed/i.test(record.status||record.event_status||'')
 const linked=useBrowse({kind:'venue',id:record.venue_id},event&&!!record.venue_id)
 const restaurantFacts=event?[]:restaurantFactRows(record.restaurant_profile)
 const images=[...new Set([event?record.image_url:record.hero_image,...list(record.photos)].filter(x=>typeof x==='string'&&safeImage(x)))],title=cleanTitle(record.title||record.name),address=record.address||record.venue_address
 const phone=String(record.phone||'').replace(/[^+\d]/g,''),external=safeLink(record.ticket_url||record.booking_link||record.website),source=safeLink(record.source_url||record.website)
 const share=async()=>{const url=new URL(window.location.origin);url.searchParams.set('item',identity(item));url.searchParams.set('kind',kind);const ok=await shareContent({title,text:[title,event?`${displayDate(record.event_date)} · ${displayTime(record.event_time)}`:record.neighborhood,'Found on GOOD TIMES'].filter(Boolean).join('\n'),url:url.toString()});setNotice(ok?'Link shared.':'Share cancelled or unavailable.')}
 return <div className="gt5-overlay gtc-overlay" role="dialog" aria-modal="true" aria-label={title} ref={ref}><article className="gt5-detail gtc-detail" data-page={event?"20":/nightlife/.test(record.category_key)?"12":/entertainment|interactive/.test(record.category_key)?"13":"11"}><header className="gtc-detail-toolbar"><button className="gt5-detail-back" onClick={onClose} aria-label="Back to results">← Back</button><button onClick={share}>Share ↗</button><button onClick={onSave} aria-pressed={saved}>{saved?'Saved ✓':'Save ♡'}</button></header>
 <div className="gtc-detail-cover"><Picture src={images[photo]} kind={event?'Event':'Place'}/>{images.length>1&&<div className="gtc-gallery-controls"><button onClick={()=>setPhoto(x=>(x-1+images.length)%images.length)} aria-label="Previous photo">‹</button><span>{photo+1} / {images.length}</span><button onClick={()=>setPhoto(x=>(x+1)%images.length)} aria-label="Next photo">›</button></div>}</div>
 <div className="gtc-detail-copy"><small className="gtc-category">{event?labelFor(record.category_key):record.venue_subcategory||record.subcategory||labelFor(record.category_key)}</small><h1>{title}</h1><p className="gtc-detail-sub">{event?`${displayDate(record.event_date)} · ${displayTime(record.event_time)}`:record.neighborhood||'Atlanta'}{record.price_range?` · ${record.price_range}`:''}</p>{event&&<p>{record.venue_name||'Location to confirm'}</p>}
 <div className="gtc-detail-primary">{external&&!blocked&&<ActionLink href={external} className="primary">{event?(record.access_type==='rsvp'?'RSVP':record.access_type==='guest_list'?'Guest list':record.ticket_url?'View tickets':'Event source'):restaurantActionLabel(record)}</ActionLink>}<button disabled={blocked} onClick={()=>onPlan(record)}>Plan around this ＋</button></div>
 {blocked&&<State title="This listing needs attention" body="It is no longer in the current eligible inventory, or its status changed. Check the official source before making plans."/>}
 {notice&&<p role="status">{notice}</p>}
 {live.status==='error'&&<p className="gtc-note" role="alert">Latest listing details could not refresh. <button onClick={live.reload}>Retry</button></p>}
 {!event&&record.restaurant_profile_state==='unavailable'&&<p className="gtc-note" role="status">Additional restaurant details could not refresh. <button onClick={live.reload}>Retry details</button></p>}
 <div className="gtc-tabs" role="tablist" aria-label="Details">{['overview',...(!event?['events']:[]),'information'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='overview'?'Overview':t==='events'?'Upcoming here':'Information'}</button>)}</div>
 {tab==='overview'&&<section className="gtc-overview">{(record.description||record.long_desc||record.short_desc)&&<p>{record.description||record.long_desc||record.short_desc}</p>}<div className="gtc-detail-facts" aria-label="Listing facts">{[[event?'Time':'Hours',event?(record.time_label||displayTime(record.event_time)):(record.hours_summary||'Confirm with venue')],['Location',address||record.venue_name||record.neighborhood],['Age / entry',record.age_requirement||record.age_range],['Dress code',record.dress_code],...restaurantFacts].filter(([,v])=>v).map(([k,v])=><div key={k}><small>{k}</small><span>{v}</span></div>)}</div>{restaurantFacts.length>0&&record.restaurant_profile?.partial&&<p className="gtc-note">Available recorded restaurant details. Additional attributes remain under review.</p>}{restaurantFacts.some(([key])=>key==='Dietary options')&&<p className="gtc-note">Confirm dietary requirements and allergen information directly with the venue.</p>}{record.is_black_owned===true&&!restaurantFacts.some(([key])=>key==='Ownership')&&<p className="gtc-note">Black-owned · recorded in GOOD TIMES</p>}<div className="gtc-detail-support">{phone&&<a href={`tel:${phone}`}>Call</a>}{address&&<ActionLink href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(address)}>Directions</ActionLink>}{onFollow&&<button onClick={onFollow}>{following?'Following ✓':'Follow + alerts'}</button>}</div><p className="gtc-note">Listings are recommendations. Check current hours, availability and entry rules before going.</p></section>}
 {tab==='events'&&<EventCollection venueId={record.id} inline {...{now,savedKeys,onEvent}} onSave={saveItem}/>}
 {event&&linked.items[0]&&<Section title="The venue"><button className="gt30-plan-strip" onClick={()=>onVenue?.(linked.items[0])}><small>PLACE</small><strong>{linked.items[0].name}</strong><span>Hours, directions and venue details →</span></button></Section>}
 {tab==='overview'&&<Section title="Make it a full plan"><div className="gt30-chips">{[['dining_culinary','Dinner'],['nightlife','Drinks'],['entertainment','Something different']].map(([key,label])=><button key={key} onClick={()=>{onClose();onExplore?.(key)}}>{label} ↗</button>)}</div><button disabled={blocked} onClick={()=>onPlan(record)}>Build around {event?'this event':'this place'}</button></Section>}
 {tab==='information'&&<section><h2>Source & details</h2>{source?<ActionLink href={source}>View source</ActionLink>:<p>No direct source link is available for this entry.</p>}{record.updated_at&&<p>Record updated {displayDate(record.updated_at.slice(0,10))}</p>}{record.verified_at&&<p>Verified {displayDate(record.verified_at.slice(0,10))}</p>}{record.photo_credit&&<p>Photo: {record.photo_credit}</p>}<p className="gtc-note">Record freshness is not a ticket, table or entry confirmation.</p><a className="gtc-support-link" href={'/support.html?listing='+encodeURIComponent(identity(item))}>Report a listing issue ↗</a></section>}
 </div></article></div>
}
export function Saved({items=[],plans=[],events=[],venues=[],onEvent,onVenue,onSave,onPlan,onExplore,onEntertainment,onBuild,onAddPlan,onSearch,session}){
 const [view,setView]=useState('all'),[query,setQuery]=useState(''),[resolved,setResolved]=useState([]),[error,setError]=useState(''),[retry,setRetry]=useState(0)
 const typed=i=>`${i.event_key?'event':'venue'}:${identity(i)}`
 useEffect(()=>{const known=new Map([...events,...venues].map(i=>[typed(i),i])),missing=items.filter(i=>!known.has(`${i.item_type}:${i.item_id}`));setResolved([...known.values()]);setError('');if(!missing.length)return;const c=new AbortController();(async()=>{for(let n=0;n<missing.length;n+=24){const ids=missing.slice(n,n+24).map(i=>({kind:i.item_type,id:i.item_id}));const r=await fetch('/api/saved-content?items='+encodeURIComponent(JSON.stringify(ids)),{signal:c.signal,cache:'no-store'}),b=await r.json();if(!r.ok||!b.ok)throw new Error('Some saved details could not refresh.');setResolved(old=>[...new Map([...old,...b.items].map(i=>[typed(i),i])).values()])}})().catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[items.map(i=>i.item_type+':'+i.item_id).join('|'),retry,events,venues])
 const lookup=new Map(resolved.map(i=>[typed(i),i])),shown=items.map(i=>lookup.get(`${i.item_type}:${i.item_id}`)).filter(Boolean).filter(i=>[i.name,i.title,i.neighborhood].join(' ').toLowerCase().includes(query.toLowerCase())),missing=items.filter(i=>!lookup.has(`${i.item_type}:${i.item_id}`)),savedKeys=new Set(items.map(i=>i.item_type+':'+i.item_id))
 const places=shown.filter(i=>!i.event_key),entertainment=shown.filter(i=>i.event_key),planRows=plans.filter(p=>String(p.name).toLowerCase().includes(query.toLowerCase())),card={savedKeys,onEvent,onVenue,onSave,onAddPlan}
 return <section className="gtc-saved gt5-saved gtc-my-good-times" data-page="30"><header className="gtc-page-heading"><div><h1>My Library</h1><small>Places, events and plans you intentionally kept.</small></div></header><div className="gtc-search"><input aria-label="Search your saved items" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search saved only…"/></div><nav className="gt30-chips" aria-label="My GOOD TIMES library">{[['all','All'],['places','Places'],['entertainment','Events'],['plans','Plans']].map(([id,label])=><button key={id} aria-pressed={view===id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav>
 {error&&<State error title="Some saved details are unavailable" body={error} action={<button onClick={()=>setRetry(x=>x+1)}>Retry</button>}/>}
 {['all','entertainment'].includes(view)&&<Section title="Saved events"><CompactRail items={entertainment} {...card}/>{!entertainment.length&&<State title="No matching saved events" action={<button onClick={onEntertainment}>Explore Entertainment</button>}/>}</Section>}
 {['all','places'].includes(view)&&<Section title="Saved places"><CompactRail items={places} {...card}/>{!places.length&&<State title="No matching saved places" action={<button onClick={onExplore}>Discover places</button>}/>}</Section>}
 {['all','plans'].includes(view)&&<Section title="Your plans">{planRows.map(p=><button className="gt30-plan-strip" key={p.id} onClick={()=>onPlan(p)}><small>{displayDate(p.itinerary_date)} · {p.status||'draft'}</small><strong>{p.name}</strong><span>{list(p.stops).length} stops · Continue →</span></button>)}{!planRows.length&&<State title="Your first plan starts here" action={<button onClick={onBuild}>Build My Night</button>}/>}</Section>}
 {missing.filter(i=>view==='all'||view===(i.item_type==='venue'?'places':'entertainment')).map(i=><div className="gtc-unavailable" key={`${i.item_type}:${i.item_id}`}><strong>Saved {i.item_type==='venue'?'place':'event'} needs attention</strong><p>Current details are unavailable. Your saved reference is retained.</p><button onClick={()=>onSave(i.item_type,i.item_id)}>Unsave</button><button onClick={i.item_type==='venue'?onExplore:onEntertainment}>Find alternatives</button></div>)}
 <div className="gt30-chips"><button onClick={onBuild}>Build from your saved ideas</button><button onClick={()=>onSearch?.(query)}>Search all GOOD TIMES ↗</button></div></section>
}
