import React,{useState} from 'react'
import {ExperienceCard,Section,State,Skeleton} from './Cards.jsx'
import {useBrowse} from './useBrowse.js'
import {discoveryWindow,filterDiscoveryEvents,EVENT_LANES} from './discovery-time.js'
import {labelFor,displayDate,shiftDate} from './model.js'
import {Sports} from './Collections.jsx'
import './all-pages.css'
export function CompactRail({items=[],savedKeys=new Set(),onEvent,onVenue,onSave,onAddPlan}){return <div className="gt30-rail">{items.map(i=><div className="gt30-card-wrap" key={`${i.event_key?'event':'venue'}:${i.event_key||i.id}`}><ExperienceCard item={i} kind={i.event_key?'event':'venue'} saved={savedKeys.has(`${i.event_key?'event':'venue'}:${i.event_key||i.id}`)} onOpen={()=>i.event_key?onEvent?.(i):onVenue?.(i)} onSave={()=>onSave?.(i.event_key?'event':'venue',i.event_key||i.id)}/>{onAddPlan&&<button className="gt30-add" onClick={()=>onAddPlan(i)}>＋ Plan</button>}</div>)}</div>}
export function MethodCards({onPlan}){return <div className="gt30-methods">{[['guided','Build It','Choose your kind of time'],['shake','Shake It','One good surprise'],['ask','Ask GOOD TIMES','Start with an idea']].map(([id,title,body])=><button key={id} onClick={()=>onPlan(id)}><strong>{title}</strong><small>{body}</small><span>↗</span></button>)}</div>}
export default function DiscoveryPages({family='entertainment',mode:initialMode='all',category:initialCategory='',events=[],venues=[],now=Date.now(),savedKeys,onEvent,onVenue,onSave,onAddPlan,onPlan,onBack,onPlaces,onSearch,taxonomy=[],plans=[],onOpenPlan}){
 const [mode,setMode]=useState(initialMode),[category,setCategory]=useState(initialCategory),[sub,setSub]=useState(''),[day,setDay]=useState(''),[band,setBand]=useState(''),[customDate,setCustomDate]=useState(''),[sort,setSort]=useState('date')
 const w=discoveryWindow(mode==='all'?'upcoming':mode,now),data=useBrowse({kind:'events',mode:customDate?null:mode==='all'?'upcoming':mode==='sports'?null:mode,from:customDate||w.from,to:customDate||w.to,category,subcategory:sub,limit:48})
 const rows=filterDiscoveryEvents(data.status==='error'?events:data.items,{mode:mode==='all'?'upcoming':mode,day,band,now}).filter(e=>(!category||e.category_key===category)&&(!sub||e.subcategory_key===sub)&&(!customDate||e.event_date===customDate)).sort((a,b)=>sort==='quality'?Number(b.quality_score||b.good_times_score||0)-Number(a.quality_score||a.good_times_score||0):0)
 const cat=taxonomy.find(c=>(c.id||c.category_key)===category),subs=cat?.subcategoryRows||cat?.subcategories||[]
 const title=family==='home'?({tonight:'Tonight in Atlanta',upcoming:'Coming up in Atlanta',weekend:'Make a weekend of it',sports:'Game day, your way'}[mode]||'This Week in Atlanta'):category?(category==='nightlife'?'Parties & Nightlife':category==='sports_watch'?'Sports Entertainment':labelFor(category)):({tonight:'Tonight',weekend:'This Weekend',all:'Entertainment'}[mode]||'Upcoming Entertainment')
 const accent=mode==='sports'||category==='sports_watch'?'sports':category==='nightlife'?'parties':category==='concerts_live_music'?'music':mode
 const card={savedKeys,onEvent,onVenue,onSave,onAddPlan}
 const changeMode=m=>{setMode(m);setDay('');setBand('');setCustomDate('')}
 return <section className={`gt30-page ${family==='entertainment'?'gtc-entertainment':''}`} data-family={accent} data-page={family==='home'?{tonight:'02',upcoming:'03',sports:'04',weekend:'05'}[mode]:category==='concerts_live_music'?'17':category==='nightlife'?'18':category==='sports_watch'?'19':mode==='tonight'?'15':mode==='weekend'?'16':'14'}>
 <header className="gt30-heading">{onBack&&<button onClick={onBack} aria-label="Back to previous page">←</button>}<div><small>GOOD TIMES · ATLANTA</small><h1>{title}</h1></div><a href="/provider-onboarding">＋ Event</a></header>
 {family==='entertainment'&&<div className="gtc-search"><input aria-label="Search Entertainment" placeholder="Clubs, concerts, sports, activities…" onKeyDown={e=>{if(e.key==='Enter')onSearch?.(e.currentTarget.value)}}/><button onClick={e=>onSearch?.(e.currentTarget.previousElementSibling.value)}>Search</button></div>}
 {family==='home'&&<nav className="gt30-chips" aria-label="Home editions">{[['tonight','Tonight'],['upcoming','Upcoming'],['sports','Sports'],['weekend','Weekend']].map(([id,label])=><button key={id} className={mode===id?'active':''} onClick={()=>changeMode(id)}>{label}</button>)}</nav>}
 {mode==='sports'||category==='sports_watch'?<Sports embedded {...{now,savedKeys,onEvent,onSave,onPlaces}} onBack={()=>{setCategory('');changeMode('upcoming')}}/>:<>
 <div className="gt30-chips" aria-label="Time window">{(family==='home'&&mode==='upcoming'?[['week','This Week'],['next-week','Next Week'],['month','Next 30 Days'],['upcoming','Upcoming']]:[['all','All'],['tonight','Tonight'],['weekend','This Weekend'],['upcoming','Upcoming'],['month','This Month']]).map(([id,label])=><button key={id} aria-pressed={mode===id} className={mode===id?'active':''} onClick={()=>changeMode(id)}>{label}</button>)}</div>
 {['upcoming','month','week','next-week'].includes(mode)&&<div className="gtc-controls"><label>Date<input type="date" value={customDate} onChange={e=>setCustomDate(e.target.value)}/></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Date & time</option><option value="quality">Recommended</option></select></label>{customDate&&<button onClick={()=>setCustomDate('')}>Clear date</button>}</div>}
 {mode==='weekend'&&<div className="gt30-chips" aria-label="Weekend day"><button className={!day?'active':''} onClick={()=>setDay('')}>All Weekend</button>{[0,1,2].map(n=>{const d=shiftDate(w.from,n);return <button key={d} className={day===d?'active':''} onClick={()=>setDay(d)}>{displayDate(d)}</button>})}</div>}
 {['tonight','weekend'].includes(mode)&&<div className="gt30-chips" aria-label="Time of day">{[['','Any time'],['soon','Starting Soon'],['day','Daytime'],['dinner','Dinner'],['night','Night'],['late','After 11']].map(([id,label])=><button key={id} className={band===id?'active':''} onClick={()=>setBand(id)}>{label}</button>)}</div>}
 <nav className="gt30-chips" aria-label="Entertainment categories"><button onClick={()=>{setCategory('');setSub('')}} className={!category?'active':''}>All categories</button>{EVENT_LANES.map(([id,label])=><button key={id} className={category===id?'active':''} onClick={()=>{setCategory(id);setSub('')}}>{label}</button>)}</nav>
 {category&&<div className="gt30-chips" aria-label="Event subcategories"><button className={!sub?'active':''} onClick={()=>setSub('')}>All {labelFor(category)}</button>{subs.map(s=><button key={s.subcategory_key||s.id} className={sub===(s.subcategory_key||s.id)?'active':''} onClick={()=>setSub(s.subcategory_key||s.id)}>{s.subcategory_name||s.name}</button>)}{!subs.length&&[...new Set(rows.map(e=>e.subcategory_key).filter(Boolean))].map(s=><button key={s} onClick={()=>setSub(s)}>{labelFor(s)}</button>)}</div>}
 {data.status==='loading'?<Skeleton count={4}/>:data.status==='error'&&<State error title="Events could not refresh" body={rows.length?'Previously loaded events are shown. Check current status before going.':'Try again or explore places.'} action={<button onClick={data.reload}>Retry</button>}/>}
 {data.status==='success'&&!rows.length&&<State title="No eligible events in this selection" body="Try another date, category or time of day, or explore verified places below." action={<button onClick={()=>{setCategory('');setSub('');setBand('');setDay('');changeMode('upcoming')}}>Explore upcoming</button>}/>}
 {!!rows.length&&(category?<Section title={sub?labelFor(sub):labelFor(category)}><CompactRail items={rows} {...card}/></Section>:<>{EVENT_LANES.map(([key,label])=>{const items=rows.filter(e=>e.category_key===key);return items.length?<Section key={key} title={label} action={<button onClick={()=>setCategory(key)}>Explore ↗</button>}><CompactRail items={items.slice(0,8)} {...card}/></Section>:null})}{rows.some(e=>!EVENT_LANES.some(([k])=>k===e.category_key))&&<Section title="More around Atlanta"><CompactRail items={rows.filter(e=>!EVENT_LANES.some(([k])=>k===e.category_key))} {...card}/></Section>}</>)}
 {data.nextCursor&&<button className="gtc-load-more" disabled={data.status==='loading-more'} onClick={data.more}>{data.status==='loading-more'?'Loading…':'More events'}</button>}
 </>}
 {plans.filter(p=>p.itinerary_date>=w.from&&p.itinerary_date<=w.to).slice(0,2).map(p=><button className="gt30-plan-strip" key={p.id} onClick={()=>onOpenPlan?.(p)}><small>YOUR PLAN</small><strong>{p.name}</strong><span>Continue →</span></button>)}
 {(family==='home'||(!rows.length&&data.status==='success'))&&<Section title={mode==='weekend'?'Places for your weekend':'Make a night of it'} subtext="Permanent places. Confirm hours and availability."><CompactRail items={venues.slice(0,8)} {...card}/></Section>}
 <Section title={mode==='sports'?'Build Game Day':'Make it yours'}><MethodCards onPlan={onPlan}/></Section><div className="gt30-chips"><button onClick={onPlaces}>Discover places ↗</button><button onClick={()=>onSearch?.('')}>Search all GOOD TIMES ↗</button></div>
 </section>
}
