import React,{useState} from 'react'
import {State} from './Cards.jsx'
export default function PlacesMap({venues=[],renderVenue}){
 const [selected,setSelected]=useState(null),[area,setArea]=useState(''),[notice,setNotice]=useState('')
 const valid=venues.filter(v=>Number.isFinite(Number(v.latitude))&&Number.isFinite(Number(v.longitude))&&v.latitude!=null&&v.longitude!=null),rows=valid.filter(v=>!area||v.neighborhood===area).slice(0,48),item=rows.find(v=>v.id===selected)||rows[0]
 const bounds=rows.length?{west:Math.min(...rows.map(v=>Number(v.longitude)))-.02,east:Math.max(...rows.map(v=>Number(v.longitude)))+.02,south:Math.min(...rows.map(v=>Number(v.latitude)))-.02,north:Math.max(...rows.map(v=>Number(v.latitude)))+.02}:{west:-84.62,east:-84.15,south:33.6,north:34.02}
 const url='https://www.openstreetmap.org/export/embed.html?'+new URLSearchParams({bbox:[bounds.west,bounds.south,bounds.east,bounds.north].join(','),layer:'mapnik',...(item?{marker:`${item.latitude},${item.longitude}`}:{})})
 return <section className="gt30-map" data-page="10"><div className="gt30-chips"><label>Area <select value={area} onChange={e=>setArea(e.target.value)}><option value="">All loaded places</option>{[...new Set(valid.map(v=>v.neighborhood).filter(Boolean))].sort().map(a=><option key={a}>{a}</option>)}</select></label><button onClick={()=>{if(!navigator.geolocation){setNotice('Location is unavailable. Browse by area.');return}navigator.geolocation.getCurrentPosition(p=>{const closest=[...valid].sort((a,b)=>Math.hypot(Number(a.latitude)-p.coords.latitude,Number(a.longitude)-p.coords.longitude)-Math.hypot(Number(b.latitude)-p.coords.latitude,Number(b.longitude)-p.coords.longitude))[0];if(closest){setArea('');setSelected(closest.id);setNotice('Closest among the loaded places selected.')}} ,()=>setNotice('Location was not available. You can still choose any area.'))}}>Near me</button></div>
 <iframe title="Atlanta places map" src={url} loading="lazy" onError={()=>setNotice('Map could not load. The place list below is still available.')}/>{notice&&<p role="status">{notice}</p>}<p className="gtc-note">{rows.length} loaded places with recorded coordinates. Select a place to show its pin. Map data © OpenStreetMap contributors.</p>
 {!rows.length?<State title="No mapped places in this selection" body="Return to the directory or choose another area."/>:<><div className="gt30-chips" aria-label="Select map place">{rows.map((v,i)=><button key={v.id} aria-pressed={item?.id===v.id} onClick={()=>setSelected(v.id)}>{i+1}. {v.name}</button>)}</div>{item&&renderVenue?.(item,true)}</>}
 </section>
}
