import React,{useState} from 'react'
import {State,Section} from './Cards.jsx'
import {itineraryWarnings} from './model.js'
export default function RadarPage({alerts=[],plans=[],follows=[],events=[],venues=[],onEvent,onVenue,onPlan,onBack,userId}){
 const [mode,setMode]=useState('For You'),[dismissed,setDismissed]=useState(()=>{try{return JSON.parse(localStorage.getItem('gt_radar_dismissed:'+userId)||'[]')}catch{return[]}})
 const dismiss=id=>setDismissed(old=>{const next=[...new Set([...old,id])].slice(-200);try{localStorage.setItem('gt_radar_dismissed:'+userId,JSON.stringify(next))}catch{}return next})
 const signals=alerts.filter(a=>!dismissed.includes(a.id)&&!a.resolved_at&&(!a.expires_at||Date.parse(a.expires_at)>Date.now())).filter((a,i,arr)=>arr.findIndex(b=>(b.dedupe_key||b.id)===(a.dedupe_key||a.id))===i)
 const open=a=>{const kind=a.object_type||a.entity_type,id=a.object_id||a.entity_id;const item=kind==='event'?events.find(e=>e.event_key===id):venues.find(v=>v.id===id);if(item)(kind==='event'?onEvent:onVenue)(item)}
 return <section className="gt30-page" data-page="28" data-family="upcoming"><header className="gt30-heading"><button onClick={onBack}>← Back</button><div><small>PERSONAL CITY INTELLIGENCE</small><h1>Your City Radar</h1></div></header><nav className="gt30-chips">{['For You','Changes','Following','City'].map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m}</button>)}</nav>
 {['For You','Changes'].includes(mode)&&<Section title="Plans to review">{plans.filter(p=>itineraryWarnings(p).length).map(p=><button className="gt30-plan-strip" key={p.id} onClick={()=>onPlan(p)}><small>BECAUSE THIS IS IN YOUR PLAN</small><strong>{p.name}</strong><span>{itineraryWarnings(p)[0]}</span><span>Review plan →</span></button>)}{!plans.some(p=>itineraryWarnings(p).length)&&<p className="gtc-note">No recorded plan issues to show.</p>}</Section>}
 {mode!=='Following'&&<Section title={mode==='City'?'Recorded city alerts':'Your updates'}>{signals.length?signals.map(a=>{const linked=(a.object_type==='event'?events:venues).some(i=>(i.event_key||i.id)===a.object_id);return <article className="gt30-plan-strip" key={a.id}><small>{String(a.alert_type||'Update').replaceAll('_',' ')}</small><strong>{a.title}</strong><p>{a.body}</p>{linked&&<button onClick={()=>open(a)}>View listing →</button>}<button onClick={()=>dismiss(a.id)}>Dismiss</button></article>}):<State title="You’re caught up" body="Recorded changes and alerts will appear here. Follow places and events you care about to make Radar useful."/>}</Section>}
 {['For You','Following'].includes(mode)&&<Section title="From your follows">{follows.filter(f=>f.is_active!==false).map(f=><div className="gt30-plan-strip" key={`${f.entity_type}:${f.entity_id}`}><small>YOU FOLLOW THIS {String(f.entity_type).toUpperCase()}</small><strong>{f.metadata?.name||'Followed listing'}</strong><span>Watching for recorded updates</span></div>)}{!follows.length&&<State title="Choose what matters to you" body="Use Follow on a place or event. Following is separate from saving."/>}</Section>}
 </section>
}
