import {normalizePlanInput,venueFits,composePlan} from './planner.js'
import React,{useEffect,useMemo,useState} from 'react'
import {ExperienceCard,State} from './Cards.jsx'
import {occurrenceUsable,displayDate} from './model.js'
export default function ShakeFlow({venues=[],events=[],savedKeys,onSave,onEvent,onVenue,onBuild,anchor,values,onChange}){
 const [category,setCategory]=useState(''),[area,setArea]=useState(''),[history,setHistory]=useState([]),[result,setResult]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setResult(null);setNotice('')},[category,area,values])
 const qualifies=i=>{try{const p=normalizePlanInput({...values,area:area||values?.area});if(category&&i.category_key!==category)return false;if(i.event_key){const r=composePlan({...p,anchorId:i.event_key},{events:[i],venues:[]});return !!r.plan?.stops.some(s=>s.id===i.event_key)}return venueFits(i,p,p.startMinute).fits}catch{return false}}
 const candidates=useMemo(()=>[...venues.filter(v=>v.status==='active'&&v.is_verified===true&&v.verification_status==='verified_current'&&Number(v.quality_score)>=55),...events.filter(e=>occurrenceUsable(e)&&Number(e.quality_score||e.good_times_score)>=55)].filter(i=>qualifies(i)&&(!category||i.category_key===category)&&(!area||i.neighborhood===area)&&(!anchor||(i.event_key||i.id)!==(anchor.event_key||anchor.id))),[venues,events,category,area,anchor,values])
 const shake=async()=>{setNotice('');setResult(null);setBusy(true);try{const eligible=candidates.filter(i=>!history.includes(i.event_key||i.id));if(!eligible.length){setResult(null);setNotice(history.length?'You’ve seen every matching option. Change a rule or start a fresh round.':'No current options match. Broaden the area or category.');return}const score=i=>Number(i.quality_score||i.good_times_score||0),top=Math.max(...eligible.map(score)),band=eligible.filter(i=>top-score(i)<=10),pick=band[Math.floor(Math.random()*band.length)],kind=pick.event_key?'events':'venue';const r=await fetch('/api/browse?'+new URLSearchParams({kind,id:pick.event_key||pick.id}),{signal:AbortSignal.timeout(9000)}),b=await r.json();if(!r.ok||!b.ok||!b.items?.length)throw new Error('That option could not be confirmed. Shake again.');setHistory(h=>[...h,pick.event_key||pick.id]);const current={...pick,...b.items[0]};if(!qualifies(current))throw new Error('That option no longer fits your rules. Try another.');setResult(current)}catch(e){setNotice(e.message||'Could not check a current option. Try again.')}finally{setBusy(false)}}
 const kind=result?.event_key?'event':'venue'
 return <section className="gt30-shake"><p className="gtc-note">One good move within your time, group and budget.</p>{anchor&&<p>Starting with {anchor.title||anchor.name}</p>}<div className="gt30-chips"><label>Category <select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Anything</option>{[...new Set([...venues,...events].map(i=>i.category_key).filter(Boolean))].map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select></label><label>Area <select value={area} onChange={e=>setArea(e.target.value)}><option value="">Anywhere</option>{[...new Set(venues.map(i=>i.neighborhood).filter(Boolean))].map(a=><option key={a}>{a}</option>)}</select></label></div><details className="gtc-shake-rules"><summary>Set a few rules</summary><div className="gtc-form"><label>Date<input type="date" value={values.date} onChange={e=>onChange({date:e.target.value})}/></label><label>People<input type="number" min="1" max="20" value={values.people} onChange={e=>onChange({people:Number(e.target.value)})}/></label><label>Start<input type="time" value={values.start} onChange={e=>onChange({start:e.target.value})}/></label><label>Finish<input type="time" value={values.end} onChange={e=>onChange({end:e.target.value})}/></label></div><label className="gtc-check"><input type="checkbox" checked={!!values.excludeNightlife} onChange={e=>onChange({excludeNightlife:e.target.checked})}/>No clubs or nightlife</label><label className="gtc-check"><input type="checkbox" checked={!!values.adultOnly} onChange={e=>onChange({adultOnly:e.target.checked})}/>Everyone is 21 or older</label><label className="gtc-check"><input type="checkbox" checked={!!values.allowUnknownHours} onChange={e=>onChange({allowUnknownHours:e.target.checked})}/>Include places whose hours need confirmation</label></details><p className="gtc-note">{displayDate(values.date)} · {values.start}–{values.end} · {values.people} people · {values.budget||'No price band'}</p><button className="gt30-shake-control" disabled={busy} onClick={shake}>{busy?'Checking your move…':result?'Shake Again':'SHAKE'}</button>{notice&&<State title="A little adjustment" body={notice} action={history.length?<button onClick={()=>{setHistory([]);setNotice('New round ready.')}}>Start a fresh round</button>:null}/>}{result&&<><h2>Your move</h2><ExperienceCard item={result} kind={kind} saved={savedKeys.has(`${kind}:${result.event_key||result.id}`)} onOpen={()=>kind==='event'?onEvent(result):onVenue(result)} onSave={()=>onSave(kind,result.event_key||result.id)}/><p className="gtc-note">Why this: current listing{category?' · your chosen category':''}{area?' · '+area:''}. {kind==='event'?displayDate(result.event_date):'Confirm venue hours before going.'}</p><div className="gt30-chips"><button onClick={()=>kind==='event'?onEvent(result):onVenue(result)}>Keep It · view details</button><button onClick={()=>onBuild(result,{area:area||values.area})}>Build the Night</button></div></>}</section>
}
