import React,{useMemo,useState} from 'react'
import {ExperienceCard,State} from './Cards.jsx'
import {occurrenceUsable,displayDate} from './model.js'
export default function ShakeFlow({venues=[],events=[],savedKeys,onSave,onEvent,onVenue,onBuild,anchor}){
 const [category,setCategory]=useState(''),[area,setArea]=useState(''),[history,setHistory]=useState([]),[result,setResult]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const candidates=useMemo(()=>[...venues.filter(v=>v.status==='active'&&v.is_verified===true&&v.verification_status==='verified_current'&&Number(v.quality_score)>=55),...events.filter(e=>occurrenceUsable(e)&&Number(e.quality_score||e.good_times_score)>=55)].filter(i=>(!category||i.category_key===category)&&(!area||i.neighborhood===area)&&(!anchor||(i.event_key||i.id)!==(anchor.event_key||anchor.id))),[venues,events,category,area,anchor])
 const shake=async()=>{setNotice('');setBusy(true);try{const eligible=candidates.filter(i=>!history.includes(i.event_key||i.id));if(!eligible.length){setResult(null);setNotice(history.length?'You’ve seen every matching option. Change a rule or start a fresh round.':'No current options match. Broaden the area or category.');return}const score=i=>Number(i.quality_score||i.good_times_score||0),top=Math.max(...eligible.map(score)),band=eligible.filter(i=>top-score(i)<=10),pick=band[Math.floor(Math.random()*band.length)],kind=pick.event_key?'events':'venue';const r=await fetch('/api/browse?'+new URLSearchParams({kind,id:pick.event_key||pick.id}),{signal:AbortSignal.timeout(9000)}),b=await r.json();if(!r.ok||!b.ok||!b.items?.length)throw new Error('That option could not be confirmed. Shake again.');setHistory(h=>[...h,pick.event_key||pick.id]);setResult({...pick,...b.items[0]})}catch(e){setNotice(e.message||'Could not check a current option. Try again.')}finally{setBusy(false)}}
 const kind=result?.event_key?'event':'venue'
 return <section className="gt30-shake"><p className="gtc-note">One good move. Choose a category or leave it open.</p>{anchor&&<p>Starting with {anchor.title||anchor.name}</p>}<div className="gt30-chips"><label>Category <select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Anything</option>{[...new Set([...venues,...events].map(i=>i.category_key).filter(Boolean))].map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select></label><label>Area <select value={area} onChange={e=>setArea(e.target.value)}><option value="">Anywhere</option>{[...new Set(venues.map(i=>i.neighborhood).filter(Boolean))].map(a=><option key={a}>{a}</option>)}</select></label></div><button className="gt30-shake-control" disabled={busy} onClick={shake}>{busy?'Checking your move…':result?'Shake Again':'SHAKE'}</button>{notice&&<State title="A little adjustment" body={notice} action={history.length?<button onClick={()=>{setHistory([]);setNotice('New round ready.')}}>Start a fresh round</button>:null}/>}{result&&<><h2>Your move</h2><ExperienceCard item={result} kind={kind} saved={savedKeys.has(`${kind}:${result.event_key||result.id}`)} onOpen={()=>kind==='event'?onEvent(result):onVenue(result)} onSave={()=>onSave(kind,result.event_key||result.id)}/><p className="gtc-note">Why this: current listing{category?' · your chosen category':''}{area?' · '+area:''}. {kind==='event'?displayDate(result.event_date):'Confirm venue hours before going.'}</p><div className="gt30-chips"><button onClick={()=>kind==='event'?onEvent(result):onVenue(result)}>Keep It · view details</button><button onClick={()=>onBuild(result)}>Build the Night</button></div></>}</section>
}
